package com.wefyx.support.ticket;
import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import java.util.*;
import com.wefyx.support.config.AccessControl;import com.wefyx.support.config.AccessControl.Role;import com.wefyx.support.notification.NotificationService;import com.wefyx.support.user.UserRepository;
@RestController @RequestMapping("/api/tickets/{ticketId}/messages") public class TicketMessageController{
 private final TicketRepository tickets;private final TicketMessageRepository messages;private final AccessControl access;private final NotificationService notifications;private final UserRepository users;
 public TicketMessageController(TicketRepository tickets,TicketMessageRepository messages,AccessControl access,NotificationService notifications,UserRepository users){this.tickets=tickets;this.messages=messages;this.access=access;this.notifications=notifications;this.users=users;}
 @GetMapping public List<TicketMessage> list(@PathVariable Long ticketId,Authentication auth){var ticket=find(ticketId);authorize(ticket,auth);return messages.findByTicketIdOrderByCreatedAtAsc(ticketId);}
 @PostMapping @ResponseStatus(HttpStatus.CREATED) public TicketMessage send(@PathVariable Long ticketId,@RequestBody Map<String,String> body,Authentication auth){var ticket=find(ticketId);authorize(ticket,auth);String text=body.getOrDefault("message","").trim();if(text.isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Message is required");var message=new TicketMessage();message.setTicketId(ticketId);message.setSenderEmail(auth.getName());message.setSenderName(body.getOrDefault("senderName",users.findByEmailIgnoreCase(auth.getName()).map(u->u.getName()).orElse(auth.getName())));message.setSenderRole(access.role(auth).name());message.setMessage(text);var saved=messages.save(message);if(!auth.getName().equalsIgnoreCase(ticket.getCustomerEmail()))notifications.send(ticket.getCustomerEmail(),ticket.getRequirementId(),"TICKET_MESSAGE","New ticket message",ticket.getReference()+" · "+text);if(ticket.getAssigneeEmail()!=null&&!ticket.getAssigneeEmail().isBlank()&&!auth.getName().equalsIgnoreCase(ticket.getAssigneeEmail()))notifications.send(ticket.getAssigneeEmail(),ticket.getRequirementId(),"TICKET_MESSAGE","Customer replied",ticket.getReference()+" · "+text);return saved;}
 private SupportTicket find(Long id){return tickets.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Ticket not found"));}
 private void authorize(SupportTicket ticket,Authentication auth){Role role=access.role(auth);if(role==Role.SUPER_ADMIN)return;if(role==Role.CUSTOMER&&auth.getName().equalsIgnoreCase(ticket.getCustomerEmail()))return;if(role==Role.EMPLOYEE&&auth.getName().equalsIgnoreCase(ticket.getAssigneeEmail()))return;throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Only the customer or assigned employee can use this ticket chat");}
}
