import React,{useState} from 'react';
import {ActivityIndicator,Alert,KeyboardAvoidingView,Linking,Platform,Pressable,ScrollView,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {apiSend} from './api';

export default function Registration({role,onBack,onRegistered}:{role:'CUSTOMER'|'VENDOR'|'EMPLOYEE';onBack:()=>void;onRegistered:(email:string)=>void}){
 const[name,setName]=useState(''),[organization,setOrganization]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(){
  setError('');
  if(!name.trim()||!organization.trim()||!/^\S+@\S+\.\S+$/.test(email.trim())){setError('Enter your name, company and a valid email.');return;}
  if(password.length<8||password.length>72){setError('Use a password between 8 and 72 characters.');return;}
  if(password!==confirm){setError('Passwords do not match.');return;}
  if(!consent){setError('Please acknowledge the privacy policy.');return;}
  setBusy(true);try{await apiSend('/auth/register','POST',{name:name.trim(),organization:organization.trim(),email:email.trim(),password,role});setPassword('');setConfirm('');Alert.alert(role==='EMPLOYEE'?'Approval required':'Account created',role==='EMPLOYEE'?'Your registration has been submitted. An administrator must approve your account before you can sign in.':'You can now sign in with your new account.',[{text:'Back to sign in',onPress:()=>onRegistered(email.trim())}]);}catch(e){setError(e instanceof Error?e.message:'Unable to create account.');}finally{setBusy(false);}
 }
 const input={backgroundColor:'#F3F6FA',borderRadius:12,paddingHorizontal:16,paddingVertical:14,color:'#071B35',fontSize:14,marginTop:12};
 return <SafeAreaView style={{flex:1,backgroundColor:'#0443A4'}}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:24,paddingBottom:40}}><Pressable onPress={onBack}><Text style={{color:'white',fontSize:14}}>‹ Back to sign in</Text></Pressable><Text style={{color:'white',fontSize:28,fontWeight:'700',marginTop:28}}>Create {role==='VENDOR'?'vendor':role==='EMPLOYEE'?'employee':'customer'} account</Text><Text style={{color:'#D6E6FF',marginTop:8}}>Join Wefyx with your own business account.</Text><View style={{backgroundColor:'white',borderRadius:24,padding:20,marginTop:24}}><TextInput style={input} value={name} onChangeText={setName} placeholder="Full name" maxLength={120}/><TextInput style={input} value={organization} onChangeText={setOrganization} placeholder="Company / organization" maxLength={200}/><TextInput style={input} value={email} onChangeText={setEmail} placeholder="Email address" autoCapitalize="none" keyboardType="email-address" autoComplete="email" maxLength={254}/><TextInput style={input} value={password} onChangeText={setPassword} placeholder="Password (minimum 8 characters)" secureTextEntry autoComplete="new-password"/><TextInput style={input} value={confirm} onChangeText={setConfirm} placeholder="Confirm password" secureTextEntry autoComplete="new-password"/><Pressable onPress={()=>setConsent(v=>!v)} style={{flexDirection:'row',alignItems:'center',marginTop:20}}><Text style={{color:'#0443A4',fontSize:22,marginRight:10}}>{consent?'☑':'☐'}</Text><Text style={{flex:1,color:'#64748B',fontSize:12}}>I have read and acknowledge the privacy policy.</Text></Pressable><Pressable onPress={()=>Linking.openURL('https://wefyx.pro/privacy-policy')}><Text style={{color:'#0443A4',fontSize:12,marginTop:8}}>View privacy policy</Text></Pressable>{!!error&&<Text style={{color:'#DC2626',marginTop:16,fontSize:13}}>{error}</Text>}<Pressable disabled={busy} onPress={submit} style={{backgroundColor:'#0443A4',borderRadius:12,padding:16,alignItems:'center',marginTop:22}}>{busy?<ActivityIndicator color="white"/>:<Text style={{color:'white',fontWeight:'600'}}>Create account</Text>}</Pressable></View></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
