package com.wefyx.support.requirement;

public enum RequirementStatus {
    SUBMITTED,
    REQUEST_CREATED,
    ACCEPTED,
    UNDER_REVIEW,
    SENT_TO_VENDOR,
    QUOTATIONS_RECEIVED,
    AWAITING_EMPLOYEE_CONFIRMATION,
    EMPLOYEE_CONFIRMED,
    AGREED_PRICING_RECORDED,
    EMPLOYEE_DECLINED,
    CANCELLED,
    VENDOR_ACCEPTED,
    IN_PROGRESS,
    RESOLVED,
    CLOSED,
    DECLINED,
    REJECTED
}
