const BASE = import.meta.env.VITE_API_URL || "/api";
function headers(json=false){const token=localStorage.getItem("wefyx-token");return {...(json?{"Content-Type":"application/json"}:{}),...(token?{Authorization:`Bearer ${token}`}:{})}}
async function response(request){if(request.status===401){localStorage.removeItem("wefyx-token");localStorage.removeItem("wefyx-auth");window.dispatchEvent(new Event("wefyx-unauthorized"))}if(!request.ok){const body=await request.json().catch(()=>({}));const error=new Error(body.message||body.error||`Request failed: ${request.status}`);error.status=request.status;error.body=body;throw error}return request.status===204?null:request.json()}
export async function login(email,password){return response(await fetch(`${BASE}/auth/login`,{method:"POST",headers:headers(true),body:JSON.stringify({email,password})}))}
export async function get(path){const organization=localStorage.getItem("wefyx-organization")||"ALL";const scoped=path==="/users"&&organization!=="ALL"?`${path}?organization=${encodeURIComponent(organization)}`:path;const data=await response(await fetch(`${BASE}${scoped}`,{headers:headers()}));if(path==="/tickets"&&organization!=="ALL"&&Array.isArray(data))return data.filter(item=>item.customer===organization);return data}
export async function send(path,method,body){return response(await fetch(`${BASE}${path}`,{method,headers:headers(true),body:body?JSON.stringify(body):undefined}))}
export async function uploadFiles(path,files){const form=new FormData();[...files].forEach(file=>form.append("files",file));return response(await fetch(`${BASE}${path}`,{method:"POST",headers:headers(),body:form}))}
export async function downloadFile(path,fileName){const request=await fetch(`${BASE}${path}`,{headers:headers()});if(!request.ok)return response(request);const blob=await request.blob();const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=fileName||"attachment";document.body.appendChild(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export async function getProfilePhotoUrl(){const request=await fetch(`${BASE}/profile/photo`,{headers:headers()});if(request.status===404)return null;if(!request.ok)return response(request);return URL.createObjectURL(await request.blob())}
export async function uploadProfilePhoto(file){const form=new FormData();form.append("file",file);return response(await fetch(`${BASE}/profile/photo`,{method:"PUT",headers:headers(),body:form}))}
