import { useEffect, useMemo, useState } from "react";
import { Bell, CheckCircle2, ChevronRight, ClipboardList, Download, FilePlus2, Headphones, LogOut, MessageCircle, Paperclip, RefreshCw, Send, Sparkles, Ticket, X } from "lucide-react";
import { downloadFile, get, send, uploadFiles } from "./api";
import { clearDraftFiles, loadDraftFiles } from "./draftFiles";

const initialRequest = { title: "", description: "", category: "General service", priority: "Medium", quotationRequested: false };
const statusStyle = {
  SUBMITTED: "bg-blue-50 text-blue-700", ACCEPTED: "bg-emerald-50 text-emerald-700",
  UNDER_REVIEW: "bg-amber-50 text-amber-700", SENT_TO_VENDOR: "bg-violet-50 text-violet-700",
  VENDOR_ACCEPTED: "bg-indigo-50 text-indigo-700", IN_PROGRESS: "bg-cyan-50 text-cyan-700",
  RESOLVED: "bg-emerald-50 text-emerald-700", CLOSED: "bg-slate-100 text-slate-600",
  DECLINED: "bg-red-50 text-red-700", REJECTED: "bg-red-50 text-red-700",
};
const readable = (value) => String(value || "").replaceAll("_", " ").replace(/\b\w/g, (x) => x.toUpperCase());
const canChat = (item) => item && !["SUBMITTED", "DECLINED", "REJECTED"].includes(item.status);

export default function CustomerPortal({ user, onLogout, embedded = false }) {
  const draft = useMemo(() => { try { return JSON.parse(sessionStorage.getItem("wefyx-requirement-draft") || "null"); } catch { return null; } }, []);
  const shouldOpen = new URLSearchParams(window.location.search).get("new") === "1" || Boolean(draft);
  const [requests, setRequests] = useState([]);
  const [tickets, setTickets] = useState([]);
  const [notifications, setNotifications] = useState([]);
  const [showNotifications, setShowNotifications] = useState(false);
  const [loading, setLoading] = useState(true);
  const [openNew, setOpenNew] = useState(shouldOpen);
  const [selected, setSelected] = useState(null);
  const [quotes, setQuotes] = useState([]);
  const [attachments, setAttachments] = useState([]);
  const [files, setFiles] = useState([]);
  const [draftFiles, setDraftFiles] = useState([]);
  const [messages, setMessages] = useState([]);
  const [message, setMessage] = useState("");
  const [form, setForm] = useState(() => ({ ...initialRequest, ...(draft || {}) }));
  const [busy, setBusy] = useState(false);
  const [formError, setFormError] = useState("");
  const [ticketError, setTicketError] = useState("");

  const load = async () => { setLoading(true); try { const [rows, customerTickets] = await Promise.all([get("/requirements?view=customer"), get("/tickets?view=customer")]); setRequests(Array.isArray(rows) ? rows : []); setTickets(Array.isArray(customerTickets) ? customerTickets : []); } finally { setLoading(false); } };
  const loadNotifications = () => get("/notifications").then((rows) => setNotifications(Array.isArray(rows) ? rows : [])).catch(() => {});
  useEffect(() => { sessionStorage.removeItem("wefyx-requirement-draft"); loadDraftFiles().then(setDraftFiles).catch(()=>{}); load(); loadNotifications(); const timer = setInterval(() => { load(); loadNotifications(); }, 15000); return () => clearInterval(timer); }, []);

  const stats = useMemo(() => ({
    open: requests.filter((x) => !["RESOLVED", "CLOSED", "DECLINED", "REJECTED"].includes(x.status)).length,
    quotes: requests.filter((x) => x.quotationStatus === "SHARED_WITH_CUSTOMER").length,
    resolved: requests.filter((x) => x.status === "RESOLVED").length,
  }), [requests]);

  async function create(event) {
    event.preventDefault(); if (!form.title.trim() || !form.description.trim()) return; setBusy(true); setFormError("");
    try { const saved=await send("/requirements", "POST", { ...form, title: form.title.trim(), description: form.description.trim(), customerName: user.name, organization: user.organization || "" }); const pending=[...draftFiles,...files]; if(pending.length)await uploadFiles(`/requirements/${saved.id}/attachments`,pending); await clearDraftFiles().catch(()=>{}); setDraftFiles([]);setFiles([]);setForm(initialRequest); setOpenNew(false); window.history.replaceState({}, "", "/"); await load(); }
    catch (error) { setFormError(error.message || "Unable to submit this requirement."); } finally { setBusy(false); }
  }
  async function view(item) {
    setSelected(item);
    const [offers, chat, docs] = await Promise.all([get(`/requirements/${item.id}/quotations?view=customer`).catch(() => []), canChat(item) ? get(`/requirements/${item.id}/messages`).catch(() => []) : Promise.resolve([]),get(`/requirements/${item.id}/attachments`).catch(()=>[])]);
    setQuotes(offers); setMessages(chat); setAttachments(docs);
  }
  async function chooseQuote(quote) { if (!selected) return; setBusy(true); try { const updated = await send(`/requirements/${selected.id}/quotations/${quote.id}/select`, "PATCH", {}); await load(); await view(updated); } finally { setBusy(false); } }
  async function sendMessage() { if (!selected || !message.trim()) return; setBusy(true); try { await send(`/requirements/${selected.id}/messages`, "POST", { message: message.trim(), senderName: user.name, senderRole: "CUSTOMER" }); setMessage(""); setMessages(await get(`/requirements/${selected.id}/messages`)); } finally { setBusy(false); } }
  async function createTicket() { if (!selected) return; setBusy(true); setTicketError(""); try { const saved = await send("/tickets", "POST", { requirementId: selected.id }); setTickets((rows) => [saved, ...rows.filter((item) => item.id !== saved.id)]); } catch (error) { setTicketError(error.message || "Unable to create a ticket for this requirement."); } finally { setBusy(false); } }
  async function readNotification(item) { if (!item.read) { await send(`/notifications/${item.id}/read`, "PATCH", {}); setNotifications((rows) => rows.map((x) => x.id === item.id ? { ...x, read: true } : x)); } const requirement = requests.find((x) => x.id === item.requirementId); if (requirement) await view(requirement); setShowNotifications(false); }

  const selectedTicket = selected ? tickets.find((item) => String(item.requirementId) === String(selected.id)) : null;

  return <main className={`${embedded ? "min-h-[calc(100vh-80px)]" : "min-h-screen"} bg-[#f4f7fb] text-slate-900`}>
    {!embedded && <header className="border-b border-slate-200 bg-[#062346] text-white"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8">
      <div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#287bd1] text-lg font-black">W</div><div><b className="block text-lg tracking-tight">Wefyx<span className="text-blue-300">.pro</span></b><span className="text-[10px] uppercase tracking-[.16em] text-blue-200">Customer workspace</span></div></div>
      <div className="relative flex items-center gap-3"><button onClick={() => setShowNotifications((v) => !v)} className="relative grid h-10 w-10 place-items-center rounded-xl bg-white/10 text-blue-100"><Bell size={18}/>{notifications.some((x) => !x.read) && <span className="absolute right-1 top-1 h-2.5 w-2.5 rounded-full bg-red-500 ring-2 ring-[#062346]"/>}</button>
        {showNotifications && <div className="absolute right-0 top-12 z-50 max-h-96 w-[min(90vw,360px)] overflow-y-auto rounded-2xl bg-white p-2 text-slate-900 shadow-2xl ring-1 ring-slate-200"><div className="px-3 py-2 text-sm font-bold">Notifications</div>{notifications.map((n) => <button key={n.id} onClick={() => readNotification(n)} className={`w-full rounded-xl p-3 text-left ${n.read ? "" : "bg-blue-50"}`}><b className="block text-xs">{n.title}</b><span className="mt-1 block text-xs leading-5 text-slate-500">{n.message}</span></button>)}{!notifications.length && <p className="p-4 text-xs text-slate-400">No notifications yet.</p>}</div>}
        <div className="hidden text-right sm:block"><b className="block text-sm">{user.name}</b><span className="text-xs text-blue-200">Customer account</span></div><button type="button" onClick={onLogout} className="inline-flex items-center gap-2 rounded-xl border border-white/20 px-3 py-2 text-xs font-semibold hover:bg-white/10"><LogOut size={15}/> Sign out</button>
      </div>
    </div></header>}
    <section className="bg-[#0a4f94] text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-5 py-8 sm:px-8 md:flex-row md:items-center"><div><p className="text-xs font-bold tracking-[.18em] text-blue-200">CUSTOMER DASHBOARD</p><h1 className="mt-2 text-3xl font-bold">Good day, {user.name.split(" ")[0]}.</h1><p className="mt-2 text-sm text-blue-100">Submit any requirement, request quotations, and follow every update in one place.</p></div><button onClick={() => setOpenNew(true)} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-white px-5 text-sm font-bold text-[#07519a] shadow-lg hover:bg-blue-50"><FilePlus2 size={18}/> New requirement</button></div></section>
    <div className="mx-auto max-w-7xl space-y-6 px-5 py-7 sm:px-8">
      <div className="grid gap-4 sm:grid-cols-3">{[["Open requests", stats.open, ClipboardList, "text-blue-600 bg-blue-50"], ["Quotes to review", stats.quotes, Sparkles, "text-violet-600 bg-violet-50"], ["Resolved", stats.resolved, CheckCircle2, "text-emerald-600 bg-emerald-50"]].map(([label, value, Icon, tone]) => <article key={label} className="rounded-2xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className={`grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon size={20}/></div><b className="mt-4 block text-2xl">{value}</b><span className="text-sm text-slate-500">{label}</span></article>)}</div>
      <section className="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><h2 className="text-lg font-bold">My requirements</h2><p className="mt-1 text-sm text-slate-500">Live review status, communication, quotations and fulfilment updates.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold text-slate-600"><RefreshCw size={14} className={loading ? "animate-spin" : ""}/> Refresh</button></div>
        {!loading && !requests.length && <div className="p-10 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-[#1671c6]"><Headphones size={25}/></div><h3 className="mt-4 font-bold">Start with your first requirement</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Tell Wefyx what you need and our team will review it.</p><button onClick={() => setOpenNew(true)} className="mt-5 rounded-xl bg-[#0b579f] px-4 py-3 text-sm font-bold text-white">Create requirement</button></div>}
        {!!requests.length && <div className="divide-y divide-slate-100">{requests.map((item) => <button key={item.id} onClick={() => view(item)} className="flex w-full items-center gap-4 p-5 text-left transition hover:bg-slate-50"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-[#1571c6]"><ClipboardList size={19}/></div><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2"><b className="truncate">{item.title}</b><span className="text-xs text-[#1571c6]">{item.reference}</span></div><p className="mt-1 truncate text-sm text-slate-500">{item.description}</p></div><div className="hidden text-right sm:block"><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${statusStyle[item.status] || "bg-slate-100"}`}>{readable(item.status)}</span><p className="mt-2 text-xs text-slate-400">{item.quotationRequested ? readable(item.quotationStatus) : "Support request"}</p></div><ChevronRight size={18} className="text-slate-400"/></button>)}</div>}
      </section>
    </div>
    {openNew && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><form onSubmit={create} className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 className="text-xl font-bold">New requirement</h2><p className="mt-1 text-sm text-slate-500">Describe anything you need from Wefyx.</p></div><button type="button" onClick={() => setOpenNew(false)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={20}/></button></div><div className="mt-6 space-y-4"><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="h-12 w-full rounded-xl border px-4 text-sm" placeholder="What do you need?"/><textarea required value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="min-h-28 w-full rounded-xl border p-4 text-sm" placeholder="Share requirements, quantities, preferred timing, or relevant details."/><div className="grid gap-4 sm:grid-cols-2"><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })} className="h-12 rounded-xl border px-3 text-sm"><option>General service</option><option>IT support</option><option>Hardware / equipment</option><option>Software / licensing</option><option>Professional service</option><option>Other</option></select><select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })} className="h-12 rounded-xl border px-3 text-sm"><option>Low</option><option>Medium</option><option>High</option><option>Urgent</option></select></div><label className="flex items-center gap-3 rounded-xl bg-blue-50 p-4 text-sm text-[#164a7d]"><input type="checkbox" checked={form.quotationRequested} onChange={(e) => setForm({ ...form, quotationRequested: e.target.checked })} className="h-4 w-4 accent-[#0b579f]"/><span><b>Request quotations</b><small className="mt-0.5 block text-xs text-slate-500">Wefyx will collect suitable vendor offers.</small></span></label>{formError && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{formError}</p>}</div><button disabled={busy} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#0b579f] text-sm font-bold text-white disabled:opacity-60">{busy ? "Submitting…" : "Submit requirement"}<Send size={17}/></button></form></div>}
    {selected && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between gap-4"><div><span className="text-xs font-bold text-[#1571c6]">{selected.reference}</span><h2 className="mt-1 text-xl font-bold">{selected.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{selected.description}</p></div><button onClick={() => setSelected(null)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><X size={20}/></button></div><div className="mt-5 flex flex-wrap gap-2"><span className={`rounded-full px-3 py-1 text-xs font-bold ${statusStyle[selected.status] || "bg-slate-100"}`}>{readable(selected.status)}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">{readable(selected.priority)} priority</span></div>
      {(selected.status === "DECLINED" || selected.status === "REJECTED") && <div className="mt-5 rounded-2xl bg-red-50 p-4"><b className="text-sm text-red-800">Decline reason</b><p className="mt-1 text-sm text-red-700">{selected.employeeNotes || "Please contact Wefyx support for details."}</p></div>}
      <section className="mt-5 flex flex-col gap-4 rounded-2xl border border-blue-100 bg-blue-50 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="flex items-center gap-2 font-bold text-[#163e67]"><Ticket size={18}/>Support ticket</h3><p className="mt-1 text-sm text-slate-600">Requirement record ID: <b>{selected.id}</b></p>{selectedTicket && <p className="mt-1 text-sm font-semibold text-emerald-700">Ticket {selectedTicket.reference} · {readable(selectedTicket.status)}</p>}{ticketError && <p className="mt-2 text-sm font-semibold text-red-700">{ticketError}</p>}</div>{!selectedTicket && <button disabled={busy} onClick={createTicket} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-[#0b579f] px-4 text-sm font-bold text-white disabled:opacity-50"><FilePlus2 size={17}/>{busy ? "Creating…" : "Create ticket"}</button>}</section>
      <section className="mt-6 rounded-2xl border border-slate-200 p-5"><h3 className="flex items-center gap-2 font-bold"><Sparkles size={18} className="text-violet-600"/>Vendor quotations</h3>{!selected.quotationRequested && <p className="mt-3 text-sm text-slate-500">This request was submitted without a quotation request.</p>}{selected.quotationRequested && !quotes.length && <p className="mt-3 text-sm text-slate-500">Your specialist is collecting suitable quotations. Comparable offers will appear here when shared.</p>}{quotes.map((quote) => <div key={quote.id} className="mt-3 flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-4"><div><b>{quote.vendorName}</b><p className="mt-1 text-sm text-slate-500">AED {Number(quote.amount || 0).toLocaleString()} · {quote.leadTimeDays || "—"} day delivery</p>{quote.notes && <p className="mt-1 text-xs text-slate-500">{quote.notes}</p>}</div>{quote.status === "SHARED_WITH_CUSTOMER" ? <button disabled={busy} onClick={() => chooseQuote(quote)} className="rounded-lg bg-[#0b579f] px-3 py-2 text-xs font-bold text-white">Choose offer</button> : <span className="text-xs font-semibold text-slate-500">{readable(quote.status)}</span>}</div>)}</section>
      <section className="mt-5 rounded-2xl border border-blue-100 bg-blue-50 p-5"><h3 className="flex items-center gap-2 font-bold text-[#163e67]"><MessageCircle size={18}/>Requirement chat</h3>{!canChat(selected) ? <p className="mt-2 text-sm text-slate-600">Chat will open as soon as an employee accepts this requirement.</p> : <><div className="mt-3 max-h-56 space-y-2 overflow-y-auto">{messages.map((item) => <div key={item.id} className={`rounded-xl p-3 ${item.senderRole === "CUSTOMER" ? "ml-8 bg-[#0b579f] text-white" : "mr-8 bg-white"}`}><div className={`text-[10px] font-semibold ${item.senderRole === "CUSTOMER" ? "text-blue-100" : "text-[#0b579f]"}`}>{item.senderName} · {readable(item.senderRole)}</div><p className="mt-1 text-sm">{item.message}</p></div>)}{!messages.length && <p className="text-xs text-slate-500">The secure conversation is ready. Ask your assigned employee a question.</p>}</div><div className="mt-3 flex gap-2"><input value={message} onChange={(e) => setMessage(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter") sendMessage(); }} className="h-11 flex-1 rounded-xl border bg-white px-3 text-sm" placeholder="Message your Wefyx employee"/><button disabled={busy || !message.trim()} onClick={sendMessage} className="rounded-xl bg-[#0b579f] px-4 text-white disabled:opacity-40"><Send size={16}/></button></div></>}</section>
    </div></div>}
  </main>;
}
