import { useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, Building2, CheckCircle2, Clock3, Eye, Pencil, Plus, Search, Shield, Store, Trash2, UserRound, Users } from "lucide-react";
import { get, send } from "./api";
import UserModal from "./UserModal";
import UserDetailsPage from "./UserDetailsPage";

const badge={ACTIVE:"bg-emerald-50 text-emerald-600",INACTIVE:"bg-slate-100 text-slate-500",PENDING:"bg-amber-50 text-amber-600",SUSPENDED:"bg-red-50 text-red-500"};
const config={
 CUSTOMER:{singular:"Customer",plural:"Customers",description:"Customer organizations and client accounts",Icon:Building2},
 EMPLOYEE:{singular:"Employee",plural:"Employees",description:"Internal support, technical and operations team members",Icon:BriefcaseBusiness},
 VENDOR:{singular:"Vendor",plural:"Vendors",description:"Approved vendor and fulfilment partner accounts",Icon:Store},
 ALL:{singular:"User",plural:"All Users",description:"Every account across the Wefyx platform",Icon:Users},
};
function accountType(user){const role=String(user.role||"").toUpperCase();if(role.includes("CUSTOMER")||role.includes("CLIENT"))return"CUSTOMER";if(role.includes("VENDOR")||role.includes("PARTNER"))return"VENDOR";if(role.includes("SUPER")||role.includes("ADMINISTRATOR"))return"ADMIN";return"EMPLOYEE";}

export default function DynamicUsersPage({userType="ALL"}){
 const meta=config[userType]||config.ALL,[users,setUsers]=useState([]),[loading,setLoading]=useState(true),[q,setQ]=useState(""),[status,setStatus]=useState("ALL"),[page,setPage]=useState(1),[size,setSize]=useState(10),[editing,setEditing]=useState(undefined),[selected,setSelected]=useState(null),[error,setError]=useState("");
 const org=localStorage.getItem("wefyx-organization")||"ALL";
 async function load(){setLoading(true);setError("");try{const rows=await get("/users");setUsers(Array.isArray(rows)?rows:[])}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[userType]);
 const typed=useMemo(()=>users.filter(user=>userType==="ALL"||accountType(user)===userType),[users,userType]);
 const filtered=useMemo(()=>typed.filter(user=>(status==="ALL"||user.status===status)&&`${user.name} ${user.email} ${user.role} ${user.organization}`.toLowerCase().includes(q.toLowerCase())),[typed,status,q]);
 const pages=Math.max(1,Math.ceil(filtered.length/size));useEffect(()=>setPage(1),[q,status,size,userType]);
 const visible=filtered.slice((page-1)*size,page*size),count=value=>typed.filter(user=>user.status===value).length;
 async function save(form){setError("");if(editing?.id){const next={...editing,...form};try{const saved=await send(`/users/${editing.id}`,"PUT",next);setUsers(rows=>rows.map(item=>item.id===saved.id?saved:item));setEditing(undefined)}catch(e){setError(e.message)}}else{try{const saved=await send("/users","POST",{...form,role:userType==="ALL"?form.role:(form.role||userType)});setUsers(rows=>[saved,...rows]);setEditing(undefined)}catch(e){setError(e.message)}}}
 async function remove(user){if(!window.confirm(`Delete ${user.name}?`))return;try{await send(`/users/${user.id}`,"DELETE");setUsers(rows=>rows.filter(item=>item.id!==user.id))}catch(e){setError(e.message)}}
 if(selected)return <UserDetailsPage user={selected} onBack={()=>setSelected(null)}/>;
 const cards=[[`Total ${meta.plural}`,typed.length,meta.Icon,"bg-blue-50 text-brand"],["Active",count("ACTIVE"),CheckCircle2,"bg-emerald-50 text-emerald-600"],["Pending",count("PENDING"),Clock3,"bg-amber-50 text-amber-600"],["Inactive",count("INACTIVE"),UserRound,"bg-slate-100 text-slate-500"],["Suspended",count("SUSPENDED"),Shield,"bg-red-50 text-red-500"]];
 return <div className="space-y-4 p-4 lg:p-5">
  <section className="flex flex-col justify-between gap-4 rounded-2xl bg-gradient-to-r from-[#062346] to-[#0b579f] p-6 text-white sm:flex-row sm:items-center"><div><p className="text-xs font-bold tracking-[.16em] text-blue-200">USER MANAGEMENT</p><h1 className="mt-2 text-2xl font-bold">{meta.plural}</h1><p className="mt-1 text-sm text-blue-100">{meta.description}</p></div><button onClick={()=>setEditing(null)} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl bg-white px-5 text-sm font-bold text-brand"><Plus size={16}/>Add {meta.singular}</button></section>
  <div className="rounded-xl border border-blue-100 bg-blue-50 px-4 py-3 text-xs"><b className="text-brand">Organization context:</b> {org==="ALL"?"All Organizations":org}<span className="ml-2 text-slate-500">• {typed.length} {meta.plural.toLowerCase()}</span></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cards.map(([label,value,Icon,color])=><article className="card flex items-center gap-3 p-4" key={label}><div className={`grid h-10 w-10 place-items-center rounded-xl ${color}`}><Icon size={19}/></div><div><span className="text-[10px] text-slate-500">{label}</span><b className="block text-xl">{value}</b></div></article>)}</div>
  <section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div className="flex gap-2 overflow-x-auto">{["ALL","ACTIVE","INACTIVE","PENDING","SUSPENDED"].map(value=><button onClick={()=>setStatus(value)} key={value} className={`rounded-lg px-3 py-2 text-[10px] font-semibold ${status===value?"bg-brand text-white":"bg-slate-50 text-slate-500"}`}>{value}</button>)}</div><label className="flex h-10 items-center gap-2 rounded-xl border bg-slate-50 px-3 focus-within:border-brand focus-within:bg-white"><Search size={14}/><input value={q} onChange={event=>setQ(event.target.value)} className="w-56 bg-transparent text-xs outline-none" placeholder={`Search ${meta.plural.toLowerCase()}...`}/></label></div>
   {error&&<div className="border-b bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}
   <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-xs"><thead className="table-head"><tr><th className="px-4 py-3">{meta.singular}</th><th>Role</th><th>Organization</th><th>Status</th><th>Location</th><th>Joined</th><th>Actions</th></tr></thead><tbody>{visible.map(user=><tr key={user.id} className="border-t hover:bg-slate-50"><td className="px-4 py-3"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-blue-100 font-bold text-brand">{user.name.split(" ").map(part=>part[0]).join("").slice(0,2)}</div><div><b>{user.name}</b><div className="text-[9px] text-slate-400">{user.email}</div></div></div></td><td><span className="pill bg-violet-50 text-violet-600">{user.role}</span></td><td>{user.organization}</td><td><span className={`pill ${badge[user.status]||badge.INACTIVE}`}>{user.status}</span></td><td>{user.location||"—"}</td><td>{user.joinedOn?new Date(user.joinedOn).toLocaleDateString():"—"}</td><td><div className="flex gap-1"><button onClick={()=>setSelected(user)} className="icon-btn h-8 w-8" title="View details"><Eye size={14}/></button><button onClick={()=>setEditing(user)} className="icon-btn h-8 w-8" title="Edit"><Pencil size={14}/></button><button onClick={()=>remove(user)} className="icon-btn h-8 w-8 hover:text-red-500" title="Delete"><Trash2 size={14}/></button></div></td></tr>)}</tbody></table>{loading&&<div className="p-10 text-center text-sm text-slate-400">Loading {meta.plural.toLowerCase()}…</div>}{!loading&&!visible.length&&<div className="p-10 text-center text-sm text-slate-400">No {meta.plural.toLowerCase()} found.</div>}</div>
   <div className="flex flex-wrap items-center justify-between gap-3 border-t p-4 text-[11px] text-slate-500"><span>Showing {filtered.length?(page-1)*size+1:0}–{Math.min(page*size,filtered.length)} of {filtered.length} {meta.plural.toLowerCase()}</span><div className="flex gap-1"><button disabled={page===1} onClick={()=>setPage(value=>value-1)} className="icon-btn h-8 w-8">‹</button>{Array.from({length:Math.min(5,pages)},(_,index)=>{const value=pages<=5?index+1:Math.min(Math.max(1,page-2)+index,pages);return <button onClick={()=>setPage(value)} key={value} className={`icon-btn h-8 w-8 ${page===value?"border-brand text-brand":""}`}>{value}</button>})}<button disabled={page===pages} onClick={()=>setPage(value=>value+1)} className="icon-btn h-8 w-8">›</button></div><select value={size} onChange={event=>setSize(Number(event.target.value))} className="rounded-lg border px-3 py-2"><option value="10">10 / page</option><option value="20">20 / page</option><option value="50">50 / page</option></select></div>
  </section>
  {editing!==undefined&&<UserModal user={editing?.id?editing:null} accountType={userType} onClose={()=>setEditing(undefined)} onSave={save}/>}
 </div>;
}
