import { useEffect, useMemo, useState } from "react";
import { Bell, CheckCircle2, Clock3, LogOut, Ticket, UserRound } from "lucide-react";
import { get, send } from "./api";
import RequirementsPage from "./RequirementsPage";
import SupportRequestsPanel from "./SupportRequestsPanel";

const statusStyle={OPEN:"bg-blue-50 text-blue-600",IN_PROGRESS:"bg-violet-50 text-violet-600",PENDING:"bg-amber-50 text-amber-700",RESOLVED:"bg-emerald-50 text-emerald-600",CLOSED:"bg-slate-100 text-slate-500"};

export default function EmployeePortal({user,onLogout}){
  const[tickets,setTickets]=useState([]),[loading,setLoading]=useState(true),[notifications,setNotifications]=useState([]),[showNotifications,setShowNotifications]=useState(false);
  useEffect(()=>{get("/requirements").then(rows=>setTickets(Array.isArray(rows)?rows.map(r=>({...r,subject:r.title,customer:r.customerName,assignee:r.employeeName||user?.name})):[])).finally(()=>setLoading(false))},[]);
  useEffect(()=>{const load=()=>get('/notifications').then(x=>setNotifications(Array.isArray(x)?x:[])).catch(()=>{});load();const timer=setInterval(load,15000);return()=>clearInterval(timer)},[]);
  async function readNotification(item){if(!item.read){await send(`/notifications/${item.id}/read`,'PATCH',{});setNotifications(rows=>rows.map(x=>x.id===item.id?{...x,read:true}:x))}setShowNotifications(false)}
  const mine=useMemo(()=>tickets.filter(t=>!user?.name||t.assignee===user.name),[tickets,user]);
  async function update(ticket,status){const previous=ticket.status;setTickets(rows=>rows.map(t=>t.id===ticket.id?{...t,status}:t));try{await send(`/tickets/${ticket.id}/status`,"PATCH",{status})}catch{setTickets(rows=>rows.map(t=>t.id===ticket.id?{...t,status:previous}:t))}}
  const open=mine.filter(t=>!["RESOLVED","CLOSED"].includes(t.status)).length;
  return <div className="min-h-screen bg-slate-50">
    <header className="flex h-20 items-center justify-between bg-navy px-5 text-white lg:px-10"><div><b className="text-lg">Wefyx Employee Portal</b><p className="text-xs text-blue-200">Assigned work and service updates</p></div><div className="relative flex items-center gap-3"><button onClick={()=>setShowNotifications(v=>!v)} className="relative grid h-10 w-10 place-items-center rounded-xl bg-white/10"><Bell size={19}/>{notifications.some(x=>!x.read)&&<span className="absolute right-1 top-1 h-2.5 w-2.5 rounded-full bg-red-500 ring-2 ring-navy"/>}</button>{showNotifications&&<div className="absolute right-0 top-12 z-50 max-h-96 w-[min(90vw,360px)] overflow-y-auto rounded-2xl bg-white p-2 text-slate-900 shadow-2xl ring-1 ring-slate-200"> <div className="px-3 py-2 text-sm font-bold">Notifications</div>{notifications.map(n=><button key={n.id} onClick={()=>readNotification(n)} className={`w-full rounded-xl p-3 text-left ${n.read?'':'bg-blue-50'}`}><b className="block text-xs">{n.title}</b><span className="mt-1 block text-xs leading-5 text-slate-500">{n.message}</span></button>)}{!notifications.length&&<p className="p-4 text-xs text-slate-400">No notifications yet.</p>}</div>}<span className="hidden text-sm sm:block">{user?.name}</span><button onClick={onLogout} className="flex items-center gap-2 rounded-lg border border-white/20 px-3 py-2 text-xs"><LogOut size={15}/> Sign out</button></div></header>
    <main className="mx-auto max-w-7xl space-y-5 p-4 lg:p-8"><section className="rounded-2xl bg-gradient-to-r from-blue-700 to-violet-600 p-6 text-white"><p className="text-xs font-semibold text-blue-100">EMPLOYEE WORKSPACE</p><h1 className="mt-2 text-2xl font-bold">Welcome, {user?.name}</h1><p className="mt-1 text-sm text-blue-100">Review customer requirements, invite vendors, compare quotations, chat with participants and manage fulfilment.</p></section>
      <RequirementsPage user={user}/>
      <SupportRequestsPanel user={user}/>
      <div className="grid gap-3 sm:grid-cols-3">{[["Assigned",mine.length,Ticket],["In progress",open,Clock3],["Completed",mine.length-open,CheckCircle2]].map(([label,value,Icon])=><div key={label} className="card flex items-center gap-4 p-5"><div className="grid h-11 w-11 place-items-center rounded-xl bg-blue-50 text-brand"><Icon size={20}/></div><div><p className="text-xs text-slate-500">{label}</p><b className="text-2xl">{value}</b></div></div>)}</div>
      <section className="card overflow-hidden"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">My assigned tickets</h2><p className="text-xs text-slate-500">Live records from the Wefyx service desk</p></div><UserRound className="text-brand" size={20}/></div>{loading?<div className="p-12 text-center text-sm text-slate-400">Loading assigned work…</div>:<div className="divide-y">{mine.map(t=><div key={t.id} className="grid gap-3 p-5 md:grid-cols-[1fr_180px] md:items-center"><div><b className="text-sm">{t.subject}</b><p className="mt-1 text-xs text-slate-500">{t.reference} · {t.customer} · {t.category}</p></div><select value={t.status} onChange={e=>update(t,e.target.value)} className={`rounded-lg border-0 px-3 py-2 text-xs font-semibold ${statusStyle[t.status]||statusStyle.OPEN}`}>{["OPEN","IN_PROGRESS","PENDING","RESOLVED","CLOSED"].map(s=><option key={s}>{s}</option>)}</select></div>)}{!mine.length&&<div className="p-12 text-center text-sm text-slate-400">No tickets are assigned to you.</div>}</div>}</section>
    </main>
  </div>
}
