import { ArrowLeft, Bell, Camera, Database, LockKeyhole, MapPin, ShieldCheck, Smartphone } from "lucide-react";

const sections = [
  [Database, "Information we collect", <><p>We collect information that you or your organization provides when using Wefyx, including your name, business email address, organization, role, profile photo, support requests, ticket messages, asset and contract information, and files or photos you choose to attach.</p><p>We also process technical information needed to operate and secure the service, such as device model, operating-system version, app version, network status, IP address, login activity, and diagnostic events.</p></>],
  [MapPin, "Location information", <p>With your permission, Wefyx may access precise or approximate device location to provide technician tracking, service coordination, route visibility, and location-aware support. Location access is optional unless a feature requires it. You can change this permission at any time in your device settings.</p>],
  [Camera, "Photos, profile images and attachments", <p>When you choose a profile photo or attach evidence to a support request, Wefyx accesses only the images you select. We use those images to display your profile or support the relevant ticket and do not scan your complete photo library.</p>],
  [Bell, "Notifications", <p>With your permission, we send notifications about ticket assignments, technician progress, service updates, contracts, assets, security events, and other account activity. You can disable notifications in your device settings.</p>],
  [Smartphone, "How we use information", <ul><li>Provide, maintain and improve IT support and asset-rental services.</li><li>Authenticate users, preserve sessions and protect accounts.</li><li>Create, assign, update and resolve support tickets.</li><li>Manage organizations, employees, vendors, assets and contracts.</li><li>Provide technician tracking and service-status updates.</li><li>Respond to support requests and communicate important changes.</li><li>Detect misuse, investigate incidents and maintain audit records.</li></ul>],
  [ShieldCheck, "Sharing and service providers", <p>We do not sell personal information. Information may be shared with the organization that manages your Wefyx account, authorized technicians or vendors involved in delivering a requested service, infrastructure providers that process data on our behalf, or authorities when required by law. These parties receive only the information reasonably necessary for their role.</p>],
  [LockKeyhole, "Security, retention and deletion", <><p>We use access controls, encrypted transport, secure credential storage and audit logging to protect information. No system is completely secure, but we work to prevent unauthorized access, loss and misuse.</p><p>We retain information for as long as needed to provide the service, comply with legal or contractual requirements, resolve disputes and maintain security records. You may request access, correction or deletion by contacting us. Some records may be retained where required by law or a legitimate security obligation.</p></>],
];

export default function PrivacyPolicyPage() {
  return <div className="min-h-screen bg-slate-50 text-slate-800">
    <div className="border-b border-white/10 bg-[#07052d] text-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-5 sm:px-8">
      <a href="/" className="flex items-center gap-3" aria-label="Wefyx home"><div className="text-3xl font-black tracking-[-.08em] text-[#6574ff]">W</div><div><div className="text-xl font-bold">Wefyx<span className="text-violet-400">.</span>pro</div><div className="text-[10px] text-blue-100/65">IT Support & Rental Platform</div></div></a>
      <a href="/" className="flex items-center gap-2 rounded-xl border border-white/15 px-4 py-2 text-xs font-semibold text-blue-50 transition hover:bg-white/10"><ArrowLeft size={15}/> Back to sign in</a>
    </div></div>
    <main className="mx-auto max-w-5xl px-5 py-10 sm:px-8 sm:py-14">
      <section className="overflow-hidden rounded-3xl bg-[#0b0a3b] px-6 py-9 text-white shadow-xl sm:px-10 sm:py-12"><div className="inline-flex items-center gap-2 rounded-full border border-violet-300/20 bg-violet-400/10 px-3 py-1.5 text-xs font-semibold text-violet-200"><ShieldCheck size={15}/> Privacy and data protection</div><h1 className="mt-5 text-3xl font-bold tracking-tight sm:text-4xl">Privacy Policy</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-blue-100/75">This policy explains how Wefyx Pro collects, uses, shares and protects information across our website, mobile application and IT support and asset-rental services.</p><p className="mt-5 text-xs font-medium text-blue-100/55">Effective and last updated: September 1, 2026</p></section>
      <div className="mt-8 space-y-5">
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-lg font-bold text-slate-900">Who we are and policy scope</h2><p className="mt-3 text-sm leading-7 text-slate-600">Wefyx Pro provides a multivendor IT support and asset-rental platform for customers, employees, technicians, vendors and administrators. This policy applies whenever you use Wefyx services or interact with an organization using Wefyx. An employer or customer organization may separately control information entered into its workspace; its own privacy notices may also apply.</p></section>
        {sections.map(([Icon,title,content]) => <section key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-violet-50 text-violet-600"><Icon size={20}/></span><h2 className="text-lg font-bold text-slate-900">{title}</h2></div><div className="privacy-copy mt-4 space-y-3 text-sm leading-7 text-slate-600">{content}</div></section>)}
        <section className="rounded-2xl border border-violet-100 bg-violet-50 p-6 sm:p-8"><h2 className="text-lg font-bold text-slate-900">Your choices and contact</h2><p className="mt-3 text-sm leading-7 text-slate-600">You can control location, notification and photo permissions through your device settings. For privacy questions or requests to access, correct or delete personal information, contact us at <a className="font-semibold text-violet-700 underline underline-offset-2" href="mailto:support@wefyx.pro">support@wefyx.pro</a>. We may need to verify your identity and coordinate with the organization that manages your account.</p></section>
        <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-lg font-bold text-slate-900">Children and policy changes</h2><p className="mt-3 text-sm leading-7 text-slate-600">Wefyx is a business service and is not directed to children. We may update this policy as our services or legal obligations change. Material updates will be posted on this page with a revised effective date and, where appropriate, communicated through the service.</p></section>
      </div>
    </main>
    <footer className="border-t border-slate-200 bg-white px-5 py-7 text-center text-xs text-slate-500">© 2026 Wefyx Pro. Crafted and built by <a href="https://prabhatech.com" target="_blank" rel="noreferrer" className="font-semibold text-violet-600">Prabha Technologies</a>.</footer>
  </div>;
}
