import { useState } from "react";
import { ArrowRight, BriefcaseBusiness, Building2, Check, CheckCircle2, CircleUserRound, Eye, EyeOff, LockKeyhole, Mail, Phone, UserRound } from "lucide-react";
import { sendPublic } from "./api";

const blank = { name: "", organization: "", email: "", phone: "", password: "", confirm: "" };

function TopNav() {
  return <><div className="!bg-[#04162e] !text-[#dbeafe] px-5 py-2 text-center text-xs sm:flex sm:justify-between sm:px-[7%]"><span>UAE's trusted managed IT & infrastructure partner</span><span className="hidden sm:inline">24/7 Support · Dubai, UAE</span></div><header className="relative z-10 !bg-[#061b38] !text-white border-b border-white/10 px-5 py-4 sm:px-[7%]"><div className="mx-auto flex max-w-7xl items-center justify-between"><a href="/" className="!text-white leading-none"><b className="text-2xl tracking-tight">WEFYX<span className="!text-[#3f9df3]">.PRO</span></b><small className="!text-[#bfd8f5] mt-1 block text-[10px] tracking-wide">Smarter IT. Stronger Business.</small></a><nav className="flex items-center gap-4 text-sm font-semibold"><a href="/careers" className="hidden !text-[#dbeafe] hover:!text-white sm:block">Careers</a><a href="/portal" className="!text-white rounded-lg border border-white/20 px-3 py-2 hover:!bg-white/10">Sign In</a></nav></div></header></>;
}

function TextField({ label, icon: Icon, reveal = false, ...props }) {
  const [visible, setVisible] = useState(false);
  const isPassword = props.type === "password";
  return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-wide text-slate-600">{label}</span><span className="flex h-12 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 transition focus-within:border-[#1571c6] focus-within:bg-white focus-within:ring-4 focus-within:ring-blue-50"><Icon size={18} className="shrink-0 text-slate-400"/><input {...props} type={isPassword && visible ? "text" : props.type} className="w-full bg-transparent text-sm text-slate-800 outline-none placeholder:text-slate-400"/>{reveal && isPassword && <button type="button" aria-label={visible ? "Hide password" : "Show password"} onClick={() => setVisible((value) => !value)} className="grid h-8 w-8 shrink-0 place-items-center rounded-md text-slate-400 transition hover:bg-slate-200 hover:text-[#1571c6]">{visible ? <EyeOff size={18}/> : <Eye size={18}/>}</button>}</span></label>;
}

function SuccessOverlay({ email }) {
  const confetti = ["left-8 top-11 bg-[#ffcb45]","left-16 top-24 bg-[#ec4899]","right-12 top-14 bg-[#5f7cff]","right-20 top-28 bg-[#22c55e]","left-24 top-5 bg-[#22c55e]","right-28 top-5 bg-[#f97316]"];
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#04162e]/85 p-5 backdrop-blur-sm"><div className="relative w-full max-w-sm overflow-hidden rounded-[28px] bg-white px-8 py-11 text-center shadow-2xl"><div className="absolute inset-x-0 top-0 h-2 bg-gradient-to-r from-[#0b4f91] via-[#1a8ae1] to-[#61b5ff]"/>{confetti.map((item,index)=><span key={item} className={`absolute h-3 w-2 rotate-[25deg] rounded-sm ${item} animate-bounce`} style={{animationDelay:`${index*90}ms`}}/>)}<div className="relative mx-auto grid h-24 w-24 place-items-center rounded-full bg-emerald-500 text-white shadow-xl shadow-emerald-200"><span className="absolute inset-[-12px] rounded-full border border-emerald-200 animate-ping"/><span className="absolute inset-[-27px] rounded-full border border-emerald-100 animate-pulse"/><CheckCircle2 size={55}/></div><p className="mt-8 text-[11px] font-extrabold tracking-[.22em] text-[#1976c9]">WELCOME TO WEFYX</p><h2 className="mt-2 text-3xl font-bold text-[#08264d]">Account created!</h2><p className="mt-3 text-sm leading-6 text-slate-500">Your customer workspace is ready for <b className="text-slate-700">{email}</b>.</p><button type="button" onClick={() => window.location.assign("/portal")} className="mt-8 flex w-full items-center justify-center gap-2 rounded-xl bg-[#0b579f] px-5 py-3.5 text-sm font-bold text-white shadow-lg shadow-blue-100 transition hover:bg-[#084983]">Go to customer login <ArrowRight size={17}/></button><p className="mt-4 text-xs text-slate-400">Your account is active and ready to use.</p></div></div>;
}

function RegistrationForm({ employee = false }) {
  const [form, setForm] = useState(blank);
  const [consent, setConsent] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [done, setDone] = useState(false);
  const update = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  async function submit(event) {
    event.preventDefault(); setError(""); setMessage("");
    if (!form.name.trim() || !form.organization.trim() || !/^\S+@\S+\.\S+$/.test(form.email.trim())) return setError("Please enter your name, organization, and a valid work email.");
    if (!/^[+0-9][0-9() .-]{6,24}$/.test(form.phone.trim())) return setError("Please enter a valid phone number, including country code.");
    if (form.password.length < 8) return setError("Your password must contain at least 8 characters.");
    if (form.password !== form.confirm) return setError("Your passwords do not match.");
    if (!consent) return setError("Please accept the Privacy Policy to continue.");
    setBusy(true);
    try {
      const response = await sendPublic("/auth/register", "POST", { name: form.name.trim(), organization: form.organization.trim(), email: form.email.trim(), phone: form.phone.trim(), password: form.password, role: employee ? "EMPLOYEE" : "CUSTOMER" });
      if (employee) { setMessage(response.message || "Application submitted. A Wefyx administrator will review it before enabling sign in."); setForm((current) => ({ ...current, password: "", confirm: "" })); }
      else { sessionStorage.setItem("wefyx-registered-email", form.email.trim()); setDone(true); }
    } catch (requestError) { setError(requestError.message || "We could not create your account. Please try again."); }
    finally { setBusy(false); }
  }
  return <><form onSubmit={submit} className="mt-7 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><TextField label="Full name" icon={UserRound} value={form.name} onChange={update("name")} placeholder="Your full name"/><TextField label={employee ? "Current organization" : "Company / organization"} icon={Building2} value={form.organization} onChange={update("organization")} placeholder="Company name"/></div><div className="grid gap-4 sm:grid-cols-2"><TextField label="Work email" icon={Mail} value={form.email} onChange={update("email")} type="email" placeholder="you@company.com"/><TextField label="Phone number" icon={Phone} value={form.phone} onChange={update("phone")} type="tel" placeholder="+971 50 123 4567"/></div><div className="grid gap-4 sm:grid-cols-2"><TextField label="Password" icon={LockKeyhole} value={form.password} onChange={update("password")} type="password" reveal placeholder="At least 8 characters"/><TextField label="Confirm password" icon={LockKeyhole} value={form.confirm} onChange={update("confirm")} type="password" reveal placeholder="Repeat password"/></div><label className="flex items-start gap-3 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-600"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} className="mt-0.5 h-4 w-4 accent-[#1571c6]"/><span>I have read and agree to the <a className="font-bold text-[#1571c6] hover:underline" href="/privacy-policy">Privacy Policy</a>.</span></label>{error && <p className="rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}{message && <p className="rounded-lg bg-emerald-50 px-4 py-3 text-sm leading-6 text-emerald-700">{message}</p>}<button disabled={busy} className="flex h-13 w-full items-center justify-center gap-2 rounded-xl bg-[#0b579f] px-5 py-3.5 text-sm font-bold text-white shadow-lg shadow-blue-100 transition hover:bg-[#084983] disabled:opacity-70">{busy ? "Please wait…" : employee ? "Submit application" : "Create my customer account"}<ArrowRight size={17}/></button></form>{done && <SuccessOverlay email={form.email}/>}</>;
}

function Onboarding({ employee = false }) {
  const heading = employee ? "Build the future of support with us." : "Your business deserves better IT support.";
  const intro = employee ? "Apply for a Wefyx employee account. We’ll review your application and enable access once it is approved." : "Set up your customer workspace in a minute. Submit any requirement, compare quotations, and manage every step with Wefyx.";
  const benefits = employee ? ["Work directly on customer requirements", "Coordinate vendor quotations and delivery", "Access activates after administrator approval"] : ["Request any service, product, or support", "Receive and compare vendor quotations", "Track orders, assets, and conversations"];
  return <div className="min-h-screen bg-[#f3f7fb]"><TopNav/><main className="mx-auto grid min-h-[calc(100vh-79px)] max-w-7xl overflow-hidden lg:grid-cols-[.92fr_1.08fr]"><section className="relative hidden overflow-hidden bg-[#061b38] px-12 py-14 text-white lg:block"><div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_18%,rgba(33,133,232,.35),transparent_32%),radial-gradient(circle_at_90%_86%,rgba(42,83,210,.32),transparent_38%)]"/><img src="/images/home-hero-reference.png" className="absolute bottom-0 right-[-12%] w-[104%] opacity-35 mix-blend-screen" alt=""/><div className="relative z-10 flex h-full flex-col"><span className="inline-flex w-fit items-center rounded-full border border-blue-300/30 bg-blue-400/10 px-4 py-2 text-[11px] font-bold tracking-[.18em] text-blue-100">{employee ? "CAREERS AT WEFYX" : "WELCOME TO WEFYX"}</span><h1 className="mt-8 max-w-md text-5xl font-bold leading-[1.08]">{heading}</h1><p className="mt-5 max-w-md text-base leading-7 text-blue-100/75">{intro}</p><div className="mt-auto space-y-4 rounded-2xl border border-white/10 bg-white/5 p-5 backdrop-blur-sm">{benefits.map((item) => <div key={item} className="flex items-center gap-3 text-sm text-blue-50"><span className="grid h-6 w-6 place-items-center rounded-full bg-[#2384df]"><Check size={15}/></span>{item}</div>)}</div></div></section><section className="flex items-center justify-center px-5 py-10 sm:px-10"><div className="w-full max-w-xl"><div className="mb-6 lg:hidden"><span className="text-[11px] font-bold tracking-[.18em] text-[#1976c9]">{employee ? "CAREERS AT WEFYX" : "CUSTOMER REGISTRATION"}</span><h1 className="mt-2 text-3xl font-bold text-[#08264d]">{heading}</h1></div><div className="rounded-3xl bg-white p-6 shadow-xl shadow-slate-200/70 sm:p-9"><div className="flex items-start gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-blue-50 text-[#1571c6]">{employee ? <BriefcaseBusiness size={24}/> : <CircleUserRound size={24}/>}</span><div><h2 className="text-2xl font-bold text-[#08264d]">{employee ? "Employee application" : "Create customer account"}</h2><p className="mt-1 text-sm leading-5 text-slate-500">{employee ? "Administrator approval is required before you can sign in." : "Your customer workspace will be available immediately."}</p></div></div><RegistrationForm employee={employee}/><p className="mt-6 text-center text-sm text-slate-500">Already registered? <a href="/portal" className="font-bold text-[#1571c6] hover:underline">Sign in to your account</a></p></div><p className="mt-5 text-center text-xs text-slate-500">{employee ? "Need a customer account?" : "Interested in working with Wefyx?"} <a href={employee ? "/register" : "/careers"} className="font-bold text-[#1571c6] hover:underline">{employee ? "Register here" : "Visit Careers"}</a></p></div></section></main></div>;
}

export default function PublicRegistration(){ return <Onboarding/>; }
export function CareersPage(){ return <Onboarding employee/>; }
