import {useEffect,useMemo,useState} from "react";
import {get,send} from "./api";
import {Search,RefreshCw,Send,CheckCircle2,MessageCircle} from "lucide-react";

const badge={SUBMITTED:"bg-blue-50 text-blue-700",UNDER_REVIEW:"bg-amber-50 text-amber-700",SENT_TO_VENDOR:"bg-violet-50 text-violet-700",VENDOR_ACCEPTED:"bg-indigo-50 text-indigo-700",IN_PROGRESS:"bg-cyan-50 text-cyan-700",RESOLVED:"bg-emerald-50 text-emerald-700",CLOSED:"bg-slate-100 text-slate-600"};
export default function RequirementsPage({user}){
 const[rows,setRows]=useState([]),[q,setQ]=useState(""),[selected,setSelected]=useState(),[vendors,setVendors]=useState([]),[selectedVendorIds,setSelectedVendorIds]=useState([]),[notes,setNotes]=useState(""),[quotes,setQuotes]=useState([]),[messages,setMessages]=useState([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=()=>get("/requirements").then(x=>setRows(Array.isArray(x)?x:[]));useEffect(()=>{load()},[]);
 const shown=useMemo(()=>rows.filter(r=>`${r.reference} ${r.title} ${r.organization} ${r.vendorName||""}`.toLowerCase().includes(q.toLowerCase())),[rows,q]);
 async function open(r){setSelected(r);setNotes(r.employeeNotes||"");setError("");const[data,chat,directory]=await Promise.all([get(`/requirements/${r.id}/quotations`).catch(()=>[]),get(`/requirements/${r.id}/messages`).catch(()=>[]),get('/users?role=VENDOR&status=ACTIVE').catch(()=>[])]);setQuotes(data);setMessages(chat);setVendors(directory)}
 async function refreshDetail(){if(!selected)return;setQuotes(await get(`/requirements/${selected.id}/quotations`).catch(()=>[]));setMessages(await get(`/requirements/${selected.id}/messages`).catch(()=>[]))}
 async function act(action){if(!selected)return;setBusy(true);setError("");try{let saved;if(action==="accept")saved=await send(`/requirements/${selected.id}/accept`,"PATCH",{employeeName:user?.name||"Wefyx Support Team",notes});if(action==="review")saved=await send(`/requirements/${selected.id}/review`,"PATCH",{employeeName:user?.name||"Wefyx Support Team",notes});if(action==="decline")saved=await send(`/requirements/${selected.id}/decline`,"PATCH",{employeeName:user?.name||"Wefyx Support Team",notes});if(action==="invite")await send(`/requirements/${selected.id}/quotations/invite`,"POST",{vendorIds:selectedVendorIds});if(action==="share")await send(`/requirements/${selected.id}/quotations/share`,"PATCH",{});if(saved)setSelected(saved);await load();await refreshDetail()}catch(e){setError(e.message||"Unable to update this requirement.")}finally{setBusy(false)}}
 async function sendMessage(){if(!message.trim()||!selected)return;setBusy(true);setError("");try{const saved=await send(`/requirements/${selected.id}/messages`,"POST",{message:message.trim(),senderName:user?.name||"Wefyx Support Team",senderRole:"EMPLOYEE"});setMessages(current=>[...current,saved]);setMessage("")}catch(e){setError(e.message||"Unable to send the message.")}finally{setBusy(false)}}
 const quoteValue=rows.reduce((n,r)=>n+Number(r.agreedAmount||0),0);
 return <div className="space-y-4 p-4 lg:p-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["Requirements",rows.length],["Awaiting review",rows.filter(r=>r.status==="SUBMITTED").length],["With vendors",rows.filter(r=>["SENT_TO_VENDOR","VENDOR_ACCEPTED","IN_PROGRESS"].includes(r.status)).length],["Awarded value",`AED ${quoteValue.toLocaleString()}`]].map(([l,v])=><div className="card p-4" key={l}><span className="text-xs text-slate-500">{l}</span><b className="mt-1 block text-xl">{v}</b></div>)}</div>
 <div className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="font-bold">Requirements & competitive quotations</h2><p className="text-xs text-slate-500">Customer request → employee review → multiple vendor offers → customer selection → fulfilment</p></div><div className="flex items-center gap-2 rounded-lg border px-3"><Search size={15}/><input className="h-9 w-56 text-xs outline-none" placeholder="Search requirements" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={load}><RefreshCw size={14}/></button></div></div><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-xs"><thead className="table-head"><tr><th className="px-4 py-3">Requirement</th><th>Customer</th><th>Category</th><th>Status</th><th>Awarded vendor</th><th>Quotation stage</th><th>Action</th></tr></thead><tbody>{shown.map(r=><tr className="border-t" key={r.id}><td className="px-4 py-3"><b>{r.title}</b><div className="text-[10px] text-brand">{r.reference}</div></td><td>{r.organization||r.customerName}</td><td>{r.category}</td><td><span className={`pill ${badge[r.status]||"bg-slate-50"}`}>{r.status.replaceAll("_"," ")}</span></td><td>{r.vendorName||"Not awarded"}</td><td>{r.quotationRequested?r.quotationStatus.replaceAll("_"," "):"Not requested"}</td><td><button className="rounded-lg bg-brand px-3 py-2 font-semibold text-white" onClick={()=>open(r)}>Process</button></td></tr>)}</tbody></table></div></div>
 {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><h3 className="text-lg font-bold">{selected.reference} · {selected.title}</h3><p className="mt-2 text-sm text-slate-600">{selected.description}</p><textarea className="mt-4 min-h-20 w-full rounded-xl border p-3 text-sm" placeholder="Employee analysis and vendor instructions" value={notes} onChange={e=>setNotes(e.target.value)}/><div className="mt-3 flex flex-wrap gap-2">{selected.status==="SUBMITTED"?<><button disabled={busy} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40" onClick={()=>act("accept")}><CheckCircle2 className="mr-2 inline" size={16}/>Accept & open customer chat</button><button disabled={busy||!notes.trim()} className="rounded-xl border border-red-200 px-4 py-2 text-sm font-semibold text-red-600 disabled:opacity-40" onClick={()=>act("decline")}>Decline</button></>:<button disabled={busy||selected.status==="DECLINED"} className="rounded-xl border px-4 py-2 text-sm font-semibold disabled:opacity-40" onClick={()=>act("review")}><CheckCircle2 className="mr-2 inline" size={16}/>Mark reviewed</button>}</div>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}
 {selected.quotationRequested&&<section className="mt-5 rounded-xl border p-4"><h4 className="text-sm font-bold">Select registered vendors</h4><div className="mt-3 grid gap-2 sm:grid-cols-2">{vendors.map(v=><button key={v.id} onClick={()=>setSelectedVendorIds(ids=>ids.includes(v.id)?ids.filter(id=>id!==v.id):[...ids,v.id])} className={`rounded-xl border p-3 text-left ${selectedVendorIds.includes(v.id)?'border-brand bg-blue-50':'bg-white'}`}><b className="text-sm">{v.name}</b><p className="text-xs text-slate-500">{v.organization}</p></button>)}</div><button onClick={()=>act("invite")} disabled={!selectedVendorIds.length} className="mt-3 rounded-xl bg-brand px-4 py-2 text-sm font-semibold text-white disabled:opacity-40"><Send className="mr-2 inline" size={15}/>Send to {selectedVendorIds.length} vendors</button><div className="mt-4 space-y-2">{quotes.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm"><div><b>{x.vendorName}</b><p className="text-xs text-slate-500">{x.amount?`AED ${x.amount} · ${x.leadTimeDays} days`:"Awaiting vendor response"}</p></div><span className="pill bg-white">{x.status.replaceAll("_"," ")}</span></div>)}</div>{quotes.some(x=>x.status==="SUBMITTED")&&<button onClick={()=>act("share")} className="mt-4 rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Share submitted quotes with customer</button>}</section>}
 <section className="mt-5 rounded-xl border p-4"><h4 className="flex items-center gap-2 text-sm font-bold"><MessageCircle size={17}/>Customer conversation</h4><div className="mt-3 max-h-48 space-y-2 overflow-y-auto">{messages.map(x=><div key={x.id} className="rounded-xl bg-slate-50 p-3"><div className="text-[10px] font-semibold text-brand">{x.senderName} · {x.senderRole}</div><p className="mt-1 text-sm">{x.message}</p></div>)}{!messages.length&&<p className="text-xs text-slate-400">{selected.status==="SUBMITTED"?"Accept this requirement to open chat with the customer.":"No messages yet. Send the customer the first update."}</p>}</div>{selected.status!=="SUBMITTED"&&selected.status!=="DECLINED"&&<div className="mt-3 flex gap-2"><input value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();sendMessage()}}} className="h-11 flex-1 rounded-xl border px-3 text-sm" placeholder="Message the customer"/><button disabled={busy||!message.trim()} onClick={sendMessage} className="rounded-xl bg-brand px-4 text-white disabled:opacity-40"><Send size={16}/></button></div>}</section><button className="mt-5 px-3 py-2 text-sm" onClick={()=>setSelected()}>Close</button></div></div>}</div>
}
