import { useEffect, useState } from "react";
import { ArrowRight, CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, Cloud, Headphones, Menu, Monitor, Network, Search, Server, ShieldCheck, ShoppingCart, Sparkles, X, Zap, Building2, Camera, Fingerprint, Laptop, Gauge, CircleHelp, Mail, Phone, Send } from "lucide-react";

const slides = [
  { tag: "YOUR TRUSTED IT PARTNER IN THE UAE", title: <>Complete Managed IT Services<br/>For a <i>Smarter, Stronger Business.</i></>, panel: "BUILDING THE DIGITAL FOUNDATION FOR TOMORROW" },
  { tag: "DATA CENTER SOLUTIONS", title: <>Design. Build. Operate.<br/><i>Mission-Critical Data Centers.</i></>, panel: "BUILT FOR UPTIME. DESIGNED FOR SCALE." },
  { tag: "24/7 IT SUPPORT", title: <>Your Complete IT Department.<br/><i>Without the Overhead.</i></>, panel: "SUPPORT THAT NEVER STOPS." },
  { tag: "NETWORK & CYBERSECURITY", title: <>Secure. Connected.<br/><i>Always Available.</i></>, panel: "PROTECTING EVERY CONNECTION." },
  { tag: "FLEXIBLE IT RENTAL", title: <>Business Technology.<br/><i>When You Need It.</i></>, panel: "TECHNOLOGY ON YOUR TERMS." },
];
const quickServices = [[Headphones,"Managed IT Services"],[Server,"Data Center Construction"],[CircleHelp,"IT Support & Helpdesk"],[Cloud,"Cloud & Infrastructure"],[ShieldCheck,"Cybersecurity"],[Network,"Network & Wi-Fi Solutions"],[Camera,"CCTV & Physical Security"],[Fingerprint,"Biometric & Access Control"],[Laptop,"Rent IT Equipment"],[ShoppingCart,"Shop Electronics"]];
const cores = [[Headphones,"IT Support & Helpdesk","Remote Support · On-Site Support · 24/7 Helpdesk · SLA-Based Support · Incident Management"],[Network,"Network & Infrastructure","LAN · WAN · SD-WAN · Wi-Fi · Switching · Routing · Firewall · VPN · Structured Cabling"],[Cloud,"Cloud Services","Microsoft 365 · Azure · AWS · Cloud Migration · Cloud Backup · Hybrid Cloud · Virtual Servers"],[ShieldCheck,"Cybersecurity","Endpoint Protection · EDR · Firewall Management · Security Audits · MFA · Vulnerability Management"],[Server,"Data Center Services","Consultation · Design · Raised Flooring · Rack Installation · UPS · Cooling · NOC · Migration"],[Gauge,"AMC & Asset Management","Preventive Maintenance · Asset Tracking · Warranty Tracking · Lifecycle Management · Inventory"]];
const industries = ["Corporate Offices","Hospitality","Healthcare","Retail","Education","Warehousing","Logistics","Construction","Manufacturing","Real Estate","Financial Services","Professional Services"];

export default function ServiceWebsite() {
  const [menu,setMenu] = useState(false), [slide,setSlide] = useState(0), [paused,setPaused] = useState(false), [toast,setToast] = useState(""), [enquiry,setEnquiry] = useState("");
  useEffect(() => { if (paused) return; const t = setInterval(()=>setSlide(s=>(s+1)%slides.length),6000); return ()=>clearInterval(t); },[paused]);
  const message = (x) => { setToast(x); window.setTimeout(()=>setToast(""),3500); };
  const openEnquiry = (kind) => { setMenu(false); setEnquiry(kind); };
  const submitEnquiry = (event) => { event.preventDefault(); const type = enquiry === "site visit" ? "site visit" : "requirement"; setEnquiry(""); message(`Your ${type} has been received. Our team will be in touch shortly.`); };
  const current=slides[slide];
  return <div className="wefyx-public">
    <div className="wp-top"><div className="wp-shell"><span>UAE's trusted managed IT & infrastructure partner</span><span>24/7 Support &nbsp; • &nbsp; Dubai, UAE</span></div></div>
    <header className="wp-header"><div className="wp-shell wp-mainnav">
      <a className="wp-logo" href="/"><b>WEFYX<span>.PRO</span></b><small>Smarter IT. Stronger Business.</small></a>
      <div className="wp-search"><Search size={17}/><input placeholder="Search services, equipment, rentals, solutions..."/><button aria-label="Search"><Search size={16}/></button></div>
      <div className="wp-actions"><span>UAE <ChevronDown size={13}/></span><button onClick={()=>message("A Wefyx specialist is available 24/7.")}>Support</button><button onClick={()=>message("Quotation request started.")}>Request Quote</button><button aria-label="Cart"><ShoppingCart size={18}/></button><a href="/portal">Sign In</a><button className="wp-start" onClick={()=>message("Let’s get your IT plan started.")}>GET STARTED</button></div>
      <button className="wp-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>
    </div><nav className={menu?"wp-links wp-open":"wp-links"}><div className="wp-shell">{["Home","IT Services","Managed Services","Data Center","Shop Electronics","Rent Equipment","AMC","Business Solutions","Industries","About","Contact"].map((x,i)=>{const paths={"Home":"/","IT Services":"/services","Managed Services":"/services","Data Center":"/data-center","Shop Electronics":"/shop","Rent Equipment":"/rent","AMC":"/services","Business Solutions":"/services","Industries":"/about","About":"/about","Contact":"/contact"};return <a key={x} href={paths[x]}>{x}{[1,2,3,7,8].includes(i)&&<ChevronDown size={13}/>}</a>})}</div></nav></header>
    <main>
      <section className="wp-hero" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)}>
        <img src="/images/home-hero-reference.png" alt="Wefyx engineer servicing enterprise data center infrastructure"/>
        <div className="wp-shell wp-hero-inner"><div className="wp-hero-copy"><p>{current.tag}</p><h1>{current.title}</h1><div className="wp-rule"/><div className="wp-benefits"><span><Check/> Reduce IT Costs</span><span><Check/> Improve Productivity</span><span><Check/> Enhance Security</span><span><Check/> Scale with Confidence</span></div><div className="wp-hero-buttons"><button onClick={()=>openEnquiry("consultation")}>Get a Free Consultation <ArrowRight size={17}/></button><button onClick={()=>document.querySelector("#services")?.scrollIntoView({behavior:"smooth"})}>Explore Managed Services</button></div></div><aside className="wp-hero-panel"><b>{current.panel}</b><div>{["Data Centers","Cloud Infrastructure","Managed IT Services","Cybersecurity","IT Support","AMC & IT Lifecycle Management"].map(x=><span key={x}><i/> {x}</span>)}</div></aside></div>
        <div className="wp-controls"><button onClick={()=>setSlide((slide+slides.length-1)%slides.length)}><ChevronLeft/></button>{slides.map((_,i)=><button key={i} aria-label={"Slide "+(i+1)} onClick={()=>setSlide(i)} className={i===slide?"active":""}/>) }<button onClick={()=>setSlide((slide+1)%slides.length)}><ChevronRight/></button></div>
      </section>
      <section className="wp-quick"><div className="wp-shell">{quickServices.map(([Icon,title])=><a key={title} href="#services"><Icon/><span>{title}</span></a>)}</div></section>
      <section className="wp-shell wp-datacenter" id="data-center"><div className="wp-dc-photo"><img src="/images/data-center-reference.png" alt="Enterprise data center aisle"/></div><div className="wp-dc-copy"><p className="wp-eyebrow">DATA CENTER SOLUTIONS</p><h2>Design. Build. Operate.<br/><em>End-to-End Data Center Services.</em></h2><p>From strategy and design to construction, deployment and ongoing management — Wefyx delivers secure, scalable and high-performance data center solutions for modern businesses.</p><button onClick={()=>message("Data center consultation request started.")}>Explore Data Center Solutions <ArrowRight size={16}/></button></div><div className="wp-dc-panel">{["Data Center Design & Build","Power & Cooling Systems","Network & Security Infrastructure","24/7 Monitoring & Management","Migration & Modernization"].map(x=><span key={x}><Check/> {x}</span>)}<b>Scalable.<br/>Secure.<br/>Always On.</b></div></section>
      <section className="wp-shell wp-divisions"><article className="wp-division buy"><p>BUY ELECTRONICS</p><h3>Latest Technology<br/>for Your Business</h3><span>Laptops, desktops, servers, networking, accessories and enterprise technology.</span><button onClick={()=>message("Product catalogue opened.")}>Shop Now <ArrowRight size={15}/></button></article><article className="wp-division rent"><p>RENT EQUIPMENT</p><h3>Flexible Rentals<br/>for Every Need</h3><span>Short-term and long-term electronics rentals for companies and individuals.</span><button onClick={()=>message("Rental enquiry started.")}>Rent Now <ArrowRight size={15}/></button></article><article className="wp-division manage"><p>MANAGED IT SERVICES</p><h3>Your Complete<br/>IT Department</h3><span>Proactive, secure and reliable IT management at a predictable cost.</span><button onClick={()=>message("Managed IT consultation requested.")}>Learn More <ArrowRight size={15}/></button></article></section>
      <section className="wp-trust"><div className="wp-shell"><div className="wp-stats">{[["250+","Business Clients"],["150+","IT Projects Delivered"],["99.9%","Uptime Commitment"],["24/7","Support Available"],["UAE","Nationwide Coverage"]].map(([n,l])=><div key={l}><b>{n}</b><span>{l}</span></div>)}</div><p>Trusted across UAE business sectors</p><div className="wp-logos"><span>ENTERPRISE</span><span>HOSPITALITY</span><span>RETAIL</span><span>HEALTHCARE</span><span>LOGISTICS</span></div></div></section>
      <section className="wp-shell wp-core" id="services"><div className="wp-title"><p className="wp-eyebrow">MANAGED IT SERVICES</p><h2>Our Core Managed IT Services</h2><span>End-to-end IT management to keep your business running, secure and future-ready.</span></div><div className="wp-core-grid">{cores.map(([Icon,title,copy])=><article key={title}><div><Icon/></div><h3>{title}</h3><p>{copy}</p><a href="#contact">Explore Service <ArrowRight size={15}/></a></article>)}</div></section>
      <section className="wp-extended"><div className="wp-shell"><div className="wp-title light"><p>ONE TECHNOLOGY PARTNER</p><h2>Every IT Requirement.</h2></div><div className="wp-extended-grid">{[["Managed Endpoint Services","PC management · Patch updates · Remote management"],["Managed Server Services","Windows · Linux · Virtualization · Backup"],["Microsoft Services","Microsoft 365 · Teams · Azure AD · Migration"],["Backup & Disaster Recovery","Cloud backup · Recovery testing · Continuity"],["NOC Services","24/7 monitoring · Alerts · Escalation"],["IT Asset Management","Registration · Warranty · Lifecycle · Disposal"]].map(([a,b])=><div key={a}><Zap/><h3>{a}</h3><p>{b}</p></div>)}</div></div></section>
      <section className="wp-shell wp-visit"><div><p className="wp-eyebrow">ON-SITE EXPERTISE</p><h2>Need an IT Expert at Your Office?</h2><p>Book a site visit with our engineer for professional advice, technical inspection and a detailed recommendation.</p><button onClick={()=>message("Site visit booking started — AED 105 total including VAT.")}>Book Site Visit <CalendarDays size={16}/></button></div><aside><span>Site visit fee <b>AED 100</b></span><span>VAT <b>AED 5</b></span><strong>Total <b>AED 105</b></strong></aside></section>
      <section className="wp-shell wp-industries" id="industries"><div className="wp-title"><p className="wp-eyebrow">INDUSTRIES WE SUPPORT</p><h2>Technology shaped around your business.</h2></div><div>{industries.map(x=><span key={x}><Building2/>{x}</span>)}</div></section>
      <section className="wp-shell wp-quote" id="contact"><div><p className="wp-eyebrow">AI-ASSISTED PLANNING</p><h2>Get an Instant AI Quotation</h2><p>Tell us your requirements and receive a tailored IT solution with estimated pricing in minutes.</p><span><Check/> Smart recommendations</span><span><Check/> Instant estimates</span><span><Check/> Tailored solutions</span></div><button onClick={()=>message("AI quotation workflow started.")}>Try AI Quotation <Sparkles size={17}/></button></section>
    </main>
    <footer className="wp-footer"><div className="wp-shell"><div><a className="wp-logo" href="/"><b>WEFYX<span>.PRO</span></b><small>Smarter IT. Stronger Business.</small></a><p>Complete managed IT services, data center infrastructure and business technology across the UAE.</p></div><div><b>Services</b><a href="#services">Managed IT Services</a><a href="/data-center">Data Center Solutions</a><a href="#services">Cybersecurity</a></div><div><b>Company</b><a href="#contact">About Wefyx</a><a href="#contact">Contact Us</a><a href="/portal">Client Portal</a></div></div></footer>
    {enquiry && <div className="wp-modal" role="dialog" aria-modal="true" aria-labelledby="enquiry-title"><button className="wp-modal-backdrop" aria-label="Close form" onClick={()=>setEnquiry("")}/><form className="wp-enquiry" onSubmit={submitEnquiry}><button type="button" className="wp-close" aria-label="Close form" onClick={()=>setEnquiry("")}><X/></button><p className="wp-eyebrow">WEFYX PRO · UAE</p><h2 id="enquiry-title">{enquiry === "site visit" ? "Book an engineer visit" : "Tell us what you need"}</h2><p className="wp-enquiry-copy">Share a few details and a certified Wefyx specialist will respond within one business hour.</p><div className="wp-form-grid"><label>Full name<input required placeholder="Your full name" /></label><label>Work email<input required type="email" placeholder="name@company.com" /></label><label>Company<input placeholder="Company name" /></label><label>Mobile number<input required type="tel" placeholder="+971 50 123 4567" /></label><label className="wp-wide">Service<select defaultValue=""><option value="" disabled>Select a service</option><option>Managed IT Services</option><option>IT Support & Helpdesk</option><option>Cybersecurity</option><option>Data Center Solutions</option><option>Equipment Rental</option></select></label><label className="wp-wide">How can we help?<textarea required placeholder="Briefly describe your requirement..." /></label></div><div className="wp-form-foot"><span><ShieldCheck/> Your information stays private.</span><button type="submit">Send request <Send/></button></div><div className="wp-contact-mini"><span><Phone/> +971 4 555 0180</span><span><Mail/> hello@wefyx.pro</span></div></form></div>}
    {toast&&<div className="wp-toast"><Check/> {toast}</div>}
  </div>;
}
