import { useEffect, useState } from "react";
import { ArrowRight, CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, Cloud, Headphones, Menu, Monitor, Network, Search, Server, ShieldCheck, ShoppingCart, Sparkles, X, Zap, Building2, Camera, Fingerprint, Laptop, Gauge, CircleHelp, Mail, Phone, Send, MapPin, FileText, UserRound } from "lucide-react";

const slides = [
  { tag: "YOUR TRUSTED IT PARTNER IN THE UAE", title: <>Complete Managed IT Services<br/>For a <i>Smarter, Stronger Business.</i></>, panel: "BUILDING THE DIGITAL FOUNDATION FOR TOMORROW" },
  { tag: "DATA CENTER SOLUTIONS", title: <>Design. Build. Operate.<br/><i>Mission-Critical Data Centers.</i></>, panel: "BUILT FOR UPTIME. DESIGNED FOR SCALE." },
  { tag: "24/7 IT SUPPORT", title: <>Your Complete IT Department.<br/><i>Without the Overhead.</i></>, panel: "SUPPORT THAT NEVER STOPS." },
  { tag: "NETWORK & CYBERSECURITY", title: <>Secure. Connected.<br/><i>Always Available.</i></>, panel: "PROTECTING EVERY CONNECTION." },
  { tag: "FLEXIBLE IT RENTAL", title: <>Business Technology.<br/><i>When You Need It.</i></>, panel: "TECHNOLOGY ON YOUR TERMS." },
];
const quickServices = [[Headphones,"Managed IT Services"],[Server,"Data Center Construction"],[CircleHelp,"IT Support & Helpdesk"],[Cloud,"Cloud & Infrastructure"],[ShieldCheck,"Cybersecurity"],[Network,"Network & Wi-Fi Solutions"],[Camera,"CCTV & Physical Security"],[Fingerprint,"Biometric & Access Control"],[Laptop,"Rent IT Equipment"],[ShoppingCart,"Shop Electronics"]];
const cores = [[Headphones,"IT Support & Helpdesk",["Remote & on-site support","End user support","24/7 helpdesk","SLA-based support"]],[Network,"Network & Infrastructure",["Network design & setup","Wi-Fi solutions","Firewall & security","Monitoring & optimization"]],[Cloud,"Cloud Services",["Cloud migration","Microsoft 365","Cloud backup","Hybrid cloud solutions"]],[ShieldCheck,"Cybersecurity",["Threat protection","Security audits","Endpoint security","Compliance support"]],[Server,"Data Center Services",["Design & construction","Power & cooling","Rack & cabling","Operations & maintenance"]],[Gauge,"AMC & Asset Management",["Annual maintenance","Preventive maintenance","Asset tracking","Lifecycle management"]]];

export default function ServiceWebsite() {
  const [menu,setMenu] = useState(false), [slide,setSlide] = useState(0), [paused,setPaused] = useState(false), [toast,setToast] = useState(""), [enquiry,setEnquiry] = useState("");
  useEffect(() => { if (paused) return; const t = setInterval(()=>setSlide(s=>(s+1)%slides.length),6000); return ()=>clearInterval(t); },[paused]);
  const message = (x) => { setToast(x); window.setTimeout(()=>setToast(""),3500); };
  const openEnquiry = (kind) => { setMenu(false); setEnquiry(kind); };
  const submitEnquiry = (event) => { event.preventDefault(); const type = enquiry === "site visit" ? "site visit" : "requirement"; setEnquiry(""); message(`Your ${type} has been received. Our team will be in touch shortly.`); };
  const current=slides[slide];
  return <div className="wefyx-public">
    <div className="wp-top"><div className="wp-shell"><span>UAE's trusted managed IT & infrastructure partner</span><span>24/7 Support &nbsp; • &nbsp; Dubai, UAE</span></div></div>
    <header className="wp-header"><div className="wp-shell wp-mainnav">
      <a className="wp-logo" href="/"><b>Wefyx<span>.pro</span></b><small>Smarter IT. Stronger Business.</small></a>
      <div className="wp-search"><Search size={17}/><input placeholder="Search services, equipment, rentals, solutions..."/><button aria-label="Search"><Search size={16}/></button></div>
      <div className="wp-actions"><span><MapPin size={15}/> UAE <ChevronDown size={13}/></span><a href="/contact"><Headphones size={15}/> Support</a><a href="/services#requirement"><FileText size={15}/> Request Quote</a><a aria-label="Cart" href="/cart"><ShoppingCart size={18}/></a><a href="/portal"><UserRound size={15}/> Sign In</a><a className="wp-start" href="/services#requirement">Get Started</a></div>
      <button className="wp-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button>
    </div><nav className={menu?"wp-links wp-open":"wp-links"}><div className="wp-shell">{["Home","IT Services","Managed Services","Data Center","Shop Electronics","Rent Equipment","AMC","Business Solutions","Industries","About","Careers","Become a Vendor","Contact"].map((x,i)=>{const paths={"Home":"/","IT Services":"/services","Managed Services":"/services","Data Center":"/data-center","Shop Electronics":"/shop","Rent Equipment":"/rent","AMC":"/services","Business Solutions":"/services","Industries":"/about","About":"/about","Careers":"/careers","Become a Vendor":"/become-a-vendor","Contact":"/contact"};return <a key={x} href={paths[x]}>{x}{[1,2,3,7,8].includes(i)&&<ChevronDown size={13}/>}</a>})}</div></nav></header>
    <main>
      <section className="wp-hero" onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)}>
        <img src="/images/home-hero-reference.png" alt="Wefyx engineer servicing enterprise data center infrastructure"/>
        <div className="wp-shell wp-hero-inner"><div className="wp-hero-copy"><p>{current.tag}</p><h1>{current.title}</h1><span className="wp-hero-summary">From devices to data centers — we design, deploy, manage and support your entire IT infrastructure so you can focus on what matters most: your business.</span><div className="wp-benefits"><span><Check/> Reduce IT Costs</span><span><Check/> Improve Productivity</span><span><Check/> Enhance Security</span><span><Check/> Scale with Confidence</span></div><div className="wp-hero-buttons"><button onClick={()=>openEnquiry("consultation")}>Get a Free Consultation <ArrowRight size={17}/></button><button onClick={()=>document.querySelector("#services")?.scrollIntoView({behavior:"smooth"})}>Explore Managed Services</button></div></div><aside className="wp-hero-panel"><b>{current.panel}</b><div>{["Data Centers","Cloud Infrastructure","Managed IT Services","Cybersecurity","IT Support","AMC & IT Lifecycle Management"].map(x=><span key={x}><i/> {x}</span>)}</div></aside></div>
        <div className="wp-controls"><button onClick={()=>setSlide((slide+slides.length-1)%slides.length)}><ChevronLeft/></button>{slides.map((_,i)=><button key={i} aria-label={"Slide "+(i+1)} onClick={()=>setSlide(i)} className={i===slide?"active":""}/>) }<button onClick={()=>setSlide((slide+1)%slides.length)}><ChevronRight/></button></div>
      </section>
      <section className="wp-quick"><div className="wp-shell">{quickServices.map(([Icon,title])=><a key={title} href={title.includes("Rent")?"/rent":title.includes("Shop")?"/shop":title.includes("Data Center")?"/data-center":"/services"}><Icon/><span>{title}</span></a>)}</div></section>
      <section className="wp-shell wp-datacenter" id="data-center"><div className="wp-dc-photo"><img src="/images/data-center-reference.png" alt="Enterprise data center aisle"/></div><div className="wp-dc-copy"><p className="wp-eyebrow">DATA CENTER SOLUTIONS</p><h2>Design. Build. Operate.<br/><em>End-to-End Data Center Services.</em></h2><p>From strategy and design to construction, deployment and ongoing management — Wefyx delivers secure, scalable and high-performance data center solutions for modern businesses.</p><button onClick={()=>message("Data center consultation request started.")}>Explore Data Center Solutions <ArrowRight size={16}/></button></div><div className="wp-dc-panel">{["Data Center Design & Build","Power & Cooling Systems","Network & Security Infrastructure","24/7 Monitoring & Management","Migration & Modernization"].map(x=><span key={x}><Check/> {x}</span>)}<b>Scalable.<br/>Secure.<br/>Always On.</b></div></section>
      <section className="wp-shell wp-divisions"><article className="wp-division buy"><p>BUY ELECTRONICS</p><h3>Latest Technology<br/>for Your Business</h3><span>Laptops, desktops, servers, networking, accessories and enterprise technology.</span><a href="/shop">Shop Now <ArrowRight size={15}/></a></article><article className="wp-division rent"><p>RENT EQUIPMENT</p><h3>Flexible Rentals<br/>for Every Need</h3><span>Short-term and long-term electronics rentals for companies and individuals.</span><a href="/rent">Rent Now <ArrowRight size={15}/></a></article><article className="wp-division manage"><p>MANAGED IT SERVICES</p><h3>Your Complete<br/>IT Department</h3><span>Proactive, secure and reliable IT management at a predictable cost.</span><a href="/services">Learn More <ArrowRight size={15}/></a></article></section>
      <section className="wp-trust"><div className="wp-shell"><div className="wp-stats">{[["250+","Business Clients"],["150+","IT Projects Delivered"],["99.9%","Uptime Commitment"],["24/7","Support Available"],["UAE","Nationwide Coverage"]].map(([n,l])=><div key={l}><b>{n}</b><span>{l}</span></div>)}</div><p>Trusted across UAE business sectors</p><div className="wp-logos"><span>ENTERPRISE</span><span>HOSPITALITY</span><span>RETAIL</span><span>HEALTHCARE</span><span>LOGISTICS</span></div></div></section>
      <section className="wp-shell wp-core" id="services"><div className="wp-title"><h2>Our Core Managed IT Services</h2><span>End-to-end IT management to keep your business running, secure and future-ready.</span></div><div className="wp-core-grid">{cores.map(([Icon,title,items])=><article key={title}><div><Icon/></div><h3>{title}</h3><ul>{items.map(item=><li key={item}>{item}</li>)}</ul><a href="/services">Explore Service <ArrowRight size={15}/></a></article>)}</div></section>
      <section className="wp-shell wp-cta-row" id="contact"><article className="wp-visit"><div><CalendarDays className="wp-cta-icon"/><h2>Need an IT Expert at Your Office?</h2><p>Submit your requirement and review our proposal first. Once the proposal is accepted and the deal is confirmed, we will schedule the site visit.</p><a href="/services#requirement">Submit Requirement <ArrowRight size={15}/></a></div></article><article className="wp-quote"><div><h2>Get an Instant AI Quotation</h2><p>Tell us your requirements and get an AI-assisted IT solution with estimated pricing.</p><a href="/services#requirement">Try AI Quotation <ArrowRight size={15}/></a></div><ul><li><Check/> Smart recommendations</li><li><Check/> Instant estimates</li><li><Check/> Tailored solutions</li><li><Check/> Save time</li></ul></article></section>
    </main>
    <footer className="wp-footer"><div className="wp-shell"><div><a className="wp-logo" href="/"><b>Wefyx<span>.pro</span></b><small>Smarter IT. Stronger Business.</small></a></div><div><b>Solutions</b><a href="/services">Managed IT</a><a href="/data-center">Data Center</a><a href="/services">Cloud</a><a href="/services">Cybersecurity</a></div><div><b>Company</b><a href="/about">About Us</a><a href="/about">Our Projects</a><a href="/careers">Careers</a><a href="/become-a-vendor">Become a Vendor</a></div><div><b>Support</b><a href="/contact">Contact Us</a><a href="/portal">Support Portal</a><a href="/portal">Track Request</a><a href="/services#site-visit">Site Visit</a></div><div><b>Legal</b><a href="/privacy-policy">Privacy Policy</a><a href="/about">About Wefyx</a><a href="/contact">Contact</a></div><div className="wp-newsletter"><b>Stay Updated</b><p>Get the latest insights, offers and technology trends.</p><form onSubmit={e=>{e.preventDefault();message("Thanks for your interest. Please contact us for updates.")}}><input aria-label="Your email" required type="email" placeholder="Enter your email"/><button type="submit">Subscribe</button></form></div></div><div className="wp-footer-bottom"><span>© 2026 Wefyx.pro. All rights reserved.</span><span>Crafted &amp; Built by Prabha Technologies &nbsp; | &nbsp; prabhatech.com</span></div></footer>
    {enquiry && <div className="wp-modal" role="dialog" aria-modal="true" aria-labelledby="enquiry-title"><button className="wp-modal-backdrop" aria-label="Close form" onClick={()=>setEnquiry("")}/><form className="wp-enquiry" onSubmit={submitEnquiry}><button type="button" className="wp-close" aria-label="Close form" onClick={()=>setEnquiry("")}><X/></button><p className="wp-eyebrow">WEFYX PRO · UAE</p><h2 id="enquiry-title">{enquiry === "site visit" ? "Book an engineer visit" : "Tell us what you need"}</h2><p className="wp-enquiry-copy">Share a few details and a certified Wefyx specialist will respond within one business hour.</p><div className="wp-form-grid"><label>Full name<input required placeholder="Your full name" /></label><label>Work email<input required type="email" placeholder="name@company.com" /></label><label>Company<input placeholder="Company name" /></label><label>Mobile number<input required type="tel" placeholder="+971 50 123 4567" /></label><label className="wp-wide">Service<select defaultValue=""><option value="" disabled>Select a service</option><option>Managed IT Services</option><option>IT Support & Helpdesk</option><option>Cybersecurity</option><option>Data Center Solutions</option><option>Equipment Rental</option></select></label><label className="wp-wide">How can we help?<textarea required placeholder="Briefly describe your requirement..." /></label></div><div className="wp-form-foot"><span><ShieldCheck/> Your information stays private.</span><button type="submit">Send request <Send/></button></div><div className="wp-contact-mini"><span><Phone/> +971 4 555 0180</span><span><Mail/> hello@wefyx.pro</span></div></form></div>}
    {toast&&<div className="wp-toast"><Check/> {toast}</div>}
  </div>;
}
