import { useState } from "react";
import { ArrowRight, CheckCircle2, Headphones, Mail, MessageSquareText, Phone, Send, UserRound } from "lucide-react";
import { sendPublic } from "./api";
import { PublicFooter, PublicHeader } from "./RentalPages";

export default function SupportPage(){
 const[form,setForm]=useState({name:"",email:"",phone:"",subject:"",description:""}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[created,setCreated]=useState(null);
 const update=(key)=>(e)=>setForm({...form,[key]:e.target.value});
 async function submit(e){e.preventDefault();setBusy(true);setError("");try{const result=await sendPublic("/support-requests","POST",form);setCreated(result);setForm({name:"",email:"",phone:"",subject:"",description:""})}catch(err){setError(err.message||"Unable to submit support request") }finally{setBusy(false)}}
 return <div className="min-h-screen bg-[#f4f8fc] text-[#071a3a]"><PublicHeader/><main><section className="bg-[#061b38] px-5 py-14 text-white"><div className="mx-auto max-w-6xl"><p className="text-xs font-bold tracking-[.18em] text-blue-300">WEFYX PUBLIC SUPPORT</p><h1 className="mt-3 text-4xl font-bold sm:text-5xl">Talk to an expert</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-blue-100">No registration is required. Describe your issue and a Wefyx employee will review it and reply to your email.</p></div></section><section className="mx-auto grid max-w-6xl gap-6 px-5 py-10 lg:grid-cols-[1fr_340px]">
 {!created?<form onSubmit={submit} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200 sm:p-8"><div className="flex items-start gap-4"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-blue-50 text-[#126cc5]"><MessageSquareText/></span><div><h2 className="text-2xl font-bold">Create support request</h2><p className="mt-1 text-sm text-slate-500">We will send the answer to the email address provided below.</p></div></div><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Full name" icon={UserRound} value={form.name} onChange={update("name")} required/><Field label="Email address" icon={Mail} value={form.email} onChange={update("email")} type="email" required/><Field label="Phone number" icon={Phone} value={form.phone} onChange={update("phone")} placeholder="+971 50 123 4567"/><Field label="Subject" icon={Headphones} value={form.subject} onChange={update("subject")} required/></div><label className="mt-5 block text-xs font-bold uppercase tracking-wide text-slate-600">Description<textarea required maxLength={5000} value={form.description} onChange={update("description")} className="mt-2 min-h-40 w-full rounded-xl border border-slate-200 p-4 text-sm font-normal normal-case tracking-normal outline-none focus:border-blue-500 focus:ring-4 focus:ring-blue-50" placeholder="Describe the issue, error, impact and any steps already tried."/></label>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={busy} className="mt-6 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#096bd8] text-sm font-bold text-white disabled:opacity-60">{busy?"Submitting…":"Submit support request"}<Send size={17}/></button></form>:<div className="grid min-h-96 place-items-center rounded-3xl bg-white p-8 text-center shadow-sm ring-1 ring-slate-200"><div><CheckCircle2 className="mx-auto text-emerald-500" size={70}/><h2 className="mt-5 text-3xl font-bold">Request submitted</h2><p className="mt-3 text-sm text-slate-500">Your reference is <b className="text-[#096bd8]">{created.reference}</b>. A Wefyx employee will reply to <b>{created.email}</b>.</p><button onClick={()=>setCreated(null)} className="mt-7 inline-flex items-center gap-2 rounded-xl bg-[#096bd8] px-5 py-3 text-sm font-bold text-white">Create another request <ArrowRight size={16}/></button></div></div>}
 <aside className="rounded-3xl bg-[#071f43] p-7 text-white"><Headphones size={34} className="text-blue-300"/><h2 className="mt-5 text-2xl font-bold">How support works</h2><ol className="mt-6 space-y-5 text-sm text-blue-100">{["Submit your email and issue details","An employee reviews and investigates","The answer is stored and emailed to you","Reply using the reference if more help is needed"].map((x,i)=><li key={x} className="flex gap-3"><b className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-blue-500 text-xs text-white">{i+1}</b><span className="pt-1">{x}</span></li>)}</ol><p className="mt-8 border-t border-white/10 pt-6 text-xs leading-6 text-blue-200">For urgent business-impacting incidents, include “Urgent” in the subject and provide a reachable phone number.</p></aside>
 </section></main><PublicFooter/></div>
}
function Field({label,icon:Icon,...props}){return <label className="text-xs font-bold uppercase tracking-wide text-slate-600">{label}<span className="mt-2 flex h-12 items-center gap-3 rounded-xl border border-slate-200 px-4 focus-within:border-blue-500 focus-within:ring-4 focus-within:ring-blue-50"><Icon size={17} className="text-slate-400"/><input {...props} maxLength={label==="Subject"?180:254} className="w-full bg-transparent text-sm font-normal normal-case tracking-normal outline-none"/></span></label>}
