import { useEffect, useMemo, useState } from "react";
import { AlertCircle, CalendarDays, CheckCircle2, Clock3, FileText, MessageCircle, RefreshCw, Search, Send, Ticket, UserCheck, UserRound } from "lucide-react";
import { get, send } from "./api";

const statuses=["OPEN","IN_PROGRESS","PENDING","RESOLVED","CLOSED"];
const tone={OPEN:"bg-blue-50 text-blue-700 ring-blue-100",ASSIGNED:"bg-indigo-50 text-indigo-700 ring-indigo-100",IN_PROGRESS:"bg-violet-50 text-violet-700 ring-violet-100",PENDING:"bg-amber-50 text-amber-700 ring-amber-100",WAITING_CUSTOMER:"bg-orange-50 text-orange-700 ring-orange-100",RESOLVED:"bg-emerald-50 text-emerald-700 ring-emerald-100",CLOSED:"bg-slate-100 text-slate-600 ring-slate-200"};
const readable=value=>String(value||"").replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase());
const isEmployee=user=>/EMPLOYEE|TECH|ENGINEER|SUPPORT|MANAGER/i.test(user.role||"")&&user.status==="ACTIVE";
const date=value=>value?new Date(value).toLocaleString([], {dateStyle:"medium",timeStyle:"short"}):"—";
const identity=value=>String(value||"").trim().toLowerCase();

export default function TicketDeskPage({user}){
 const[tickets,setTickets]=useState([]),[employees,setEmployees]=useState([]),[selected,setSelected]=useState(null),[messages,setMessages]=useState([]),[message,setMessage]=useState(""),[query,setQuery]=useState(""),[tab,setTab]=useState("ALL"),[resolution,setResolution]=useState(""),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[chatLoading,setChatLoading]=useState(false),[error,setError]=useState(""),[viewer,setViewer]=useState(user);
 const admin=viewer?.role==="SUPER_ADMIN";
 const open=async ticket=>{setSelected(ticket);setResolution(ticket.resolution||"");setError("");setChatLoading(true);try{setMessages(await get(`/tickets/${ticket.id}/messages`))}catch(e){setMessages([]);setError(e.message||"Unable to load this conversation.")}finally{setChatLoading(false)}};
 const load=async()=>{setLoading(true);try{const[rows,people]=await Promise.all([get("/tickets"),get("/users")]);const list=Array.isArray(rows)?rows:[];setTickets(list);setEmployees(Array.isArray(people)?people.filter(isEmployee):[]);if(selected){const fresh=list.find(item=>item.id===selected.id);if(fresh)setSelected(fresh)}else if(list.length)await open(list[0])}finally{setLoading(false)}};
 useEffect(()=>{get("/auth/me").then(current=>{setViewer(current);localStorage.setItem("wefyx-user",JSON.stringify(current))}).catch(()=>setViewer(user));load()},[]);
 const shown=useMemo(()=>tickets.filter(t=>(tab==="ALL"||t.status===tab)&&`${t.reference} ${t.subject} ${t.customer} ${t.assignee}`.toLowerCase().includes(query.toLowerCase())),[tickets,tab,query]);
 const stats={open:tickets.filter(t=>!t.assigneeEmail&&!["RESOLVED","CLOSED"].includes(t.status)).length,assigned:tickets.filter(t=>t.assigneeEmail&&!["RESOLVED","CLOSED"].includes(t.status)).length,resolved:tickets.filter(t=>["RESOLVED","CLOSED"].includes(t.status)).length};
 const assignedToMe=Boolean(identity(selected?.assigneeEmail)&&identity(selected?.assigneeEmail)===identity(viewer?.email));
 function sync(saved){setSelected(saved);setTickets(rows=>rows.map(t=>t.id===saved.id?saved:t))}
 async function assign(email){setBusy(true);setError("");try{sync(await send(`/tickets/${selected.id}/assign`,"PATCH",{assigneeEmail:email}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function updateStatus(status){setBusy(true);setError("");try{sync(await send(`/tickets/${selected.id}/status`,"PATCH",{status,resolution}))}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function sendMessage(){if(!selected||!message.trim())return;setBusy(true);setError("");try{const saved=await send(`/tickets/${selected.id}/messages`,"POST",{message:message.trim(),senderName:viewer?.name||"Wefyx Employee"});setMessages(rows=>[...rows,saved]);setMessage("")}catch(e){setError(e.message||"Unable to send the message. Refresh the page and try again.")}finally{setBusy(false)}}
 return <div className="space-y-5 p-4 lg:p-6">
  <section className="rounded-2xl bg-gradient-to-r from-[#061d3a] via-[#063a70] to-[#0b579f] p-6 text-white shadow-lg"><p className="text-xs font-bold tracking-[.18em] text-blue-200">WEFYX SERVICE DESK</p><h1 className="mt-2 text-2xl font-bold">Ticket operations</h1><p className="mt-1 max-w-3xl text-sm text-blue-100">Triage incoming customer problems, assign accountable employees, communicate clearly and preserve a complete resolution history.</p></section>
  <div className="grid gap-3 sm:grid-cols-4">{[["All tickets",tickets.length,Ticket,"bg-blue-50 text-blue-700"],["Unassigned",stats.open,UserCheck,"bg-orange-50 text-orange-700"],["Active service",stats.assigned,Clock3,"bg-violet-50 text-violet-700"],["Completed",stats.resolved,CheckCircle2,"bg-emerald-50 text-emerald-700"]].map(([label,value,Icon,color])=><article key={label} className="card flex items-center gap-4 p-5"><div className={`grid h-11 w-11 place-items-center rounded-xl ${color}`}><Icon size={20}/></div><div><b className="text-2xl">{value}</b><p className="text-xs text-slate-500">{label}</p></div></article>)}</div>
  <div className="grid min-h-[720px] gap-5 xl:grid-cols-[360px_minmax(0,1fr)]">
   <aside className="card flex min-h-0 flex-col overflow-hidden"><div className="border-b p-4"><div className="flex items-center justify-between"><div><h2 className="font-bold">Service queue</h2><p className="mt-1 text-xs text-slate-500">{shown.length} visible · {tickets.length} total</p></div><button onClick={load} className="icon-btn"><RefreshCw size={16} className={loading?"animate-spin":""}/></button></div><label className="mt-4 flex h-10 items-center gap-2 rounded-xl border bg-slate-50 px-3 focus-within:border-brand focus-within:bg-white"><Search size={15} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent text-xs outline-none" placeholder="Reference, customer or subject"/></label><select value={tab} onChange={e=>setTab(e.target.value)} className="mt-3 h-10 w-full rounded-xl border bg-white px-3 text-xs font-semibold"><option value="ALL">All statuses</option>{statuses.map(status=><option key={status}>{status}</option>)}</select></div><div className="min-h-0 flex-1 divide-y overflow-y-auto">{shown.map(ticket=><button key={ticket.id} onClick={()=>open(ticket)} className={`w-full p-4 text-left transition ${selected?.id===ticket.id?"bg-blue-50 shadow-[inset_3px_0_0_#1671c6]":"hover:bg-slate-50"}`}><div className="flex items-start justify-between gap-2"><span className="text-[10px] font-bold text-brand">{ticket.reference}</span><span className={`rounded-full px-2 py-1 text-[9px] font-bold ring-1 ${tone[ticket.status]||tone.OPEN}`}>{readable(ticket.status)}</span></div><b className="mt-2 block line-clamp-2 text-sm leading-5">{ticket.subject}</b><p className="mt-1 truncate text-xs text-slate-500">{ticket.customer}</p><div className="mt-3 flex items-center justify-between text-[10px] text-slate-400"><span>{ticket.assignee||"Unassigned"}</span><span>{ticket.priority}</span></div></button>)}{!loading&&!shown.length&&<div className="p-10 text-center text-xs text-slate-400">No tickets match this queue.</div>}</div></aside>
   <main className="min-w-0">{selected?<div className="grid gap-5 2xl:grid-cols-[minmax(0,1fr)_370px]">
    <div className="space-y-5"><section className="card overflow-hidden"><div className="border-b bg-gradient-to-r from-slate-50 to-blue-50 p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-brand">{selected.reference}</span>{selected.requirementId&&<span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-semibold text-slate-500 ring-1 ring-slate-200">Requirement #{selected.requirementId}</span>}</div><h2 className="mt-2 text-2xl font-bold">{selected.subject}</h2><p className="mt-2 text-sm text-slate-500">{selected.customer} · {selected.customerEmail}</p></div><span className={`h-fit w-fit rounded-full px-3 py-2 text-xs font-bold ring-1 ${tone[selected.status]||tone.OPEN}`}>{readable(selected.status)}</span></div></div><div className="p-6"><p className="text-sm leading-7 text-slate-600">{selected.description||"No customer description was supplied."}</p><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["Priority",selected.priority,AlertCircle],["Category",selected.category||"General",FileText],["Created",date(selected.createdAt),CalendarDays]].map(([label,value,Icon])=><div key={label} className="rounded-xl border bg-slate-50 p-4"><Icon size={16} className="text-brand"/><span className="mt-2 block text-[10px] font-bold text-slate-400">{label.toUpperCase()}</span><b className="mt-1 block text-xs">{value}</b></div>)}</div></div></section>
     <section className="card p-6"><h3 className="font-bold">Ownership and service status</h3><p className="mt-1 text-xs text-slate-500">Every active ticket must have a responsible employee before work begins.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold text-slate-600">Assigned employee{admin?<select disabled={busy} value={selected.assigneeEmail||""} onChange={e=>e.target.value&&assign(e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-3 font-normal"><option value="">Unassigned — select employee</option>{employees.map(employee=><option key={employee.id} value={employee.email}>{employee.name} · {employee.email}</option>)}</select>:<div className="mt-2 rounded-xl border bg-slate-50 p-3"><b>{selected.assignee||"Unassigned"}</b>{!assignedToMe&&<button disabled={busy||!viewer?.email} onClick={()=>assign(viewer?.email)} className="mt-3 block h-10 w-full rounded-lg bg-brand font-bold text-white disabled:opacity-40">Assign to me</button>}</div>}</label><label className="text-xs font-bold text-slate-600">Service status<select disabled={busy||(!admin&&!assignedToMe)} value={selected.status} onChange={e=>updateStatus(e.target.value)} className="mt-2 h-12 w-full rounded-xl border px-3 font-normal">{statuses.map(status=><option key={status}>{status}</option>)}</select></label></div>{(admin||assignedToMe)&&<label className="mt-5 block text-xs font-bold text-slate-600">Resolution notes <span className="font-normal text-slate-400">Required before selecting Resolved</span><textarea value={resolution} onChange={e=>setResolution(e.target.value)} className="mt-2 min-h-28 w-full rounded-xl border p-3 font-normal leading-6 outline-none focus:border-brand" placeholder="Document the root cause, work completed and customer next steps"/></label>}{selected.resolution&&<div className="mt-5 rounded-xl border border-emerald-100 bg-emerald-50 p-4"><b className="text-sm text-emerald-800">Recorded resolution</b><p className="mt-1 text-sm leading-6 text-emerald-700">{selected.resolution}</p></div>}{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{error}</p>}</section></div>
    <section className="card flex max-h-[720px] min-h-[620px] flex-col overflow-hidden"><div className="border-b p-5"><h3 className="flex items-center gap-2 font-bold"><MessageCircle size={18} className="text-brand"/>Customer conversation</h3><p className="mt-1 text-xs text-slate-500">Permanent communication history</p></div><div className="min-h-0 flex-1 space-y-4 overflow-y-auto bg-slate-50/70 p-4">{chatLoading?<div className="py-16 text-center text-xs text-slate-400">Loading conversation…</div>:messages.map(item=><div key={item.id} className={`flex ${item.senderRole==="CUSTOMER"?"justify-start":"justify-end"}`}><div className={`max-w-[90%] rounded-2xl px-4 py-3 shadow-sm ${item.senderRole==="CUSTOMER"?"rounded-bl-md bg-white ring-1 ring-slate-200":"rounded-br-md bg-brand text-white"}`}><div className={`text-[10px] font-bold ${item.senderRole==="CUSTOMER"?"text-brand":"text-blue-100"}`}>{item.senderName}</div><p className="mt-1 text-sm leading-6">{item.message}</p><div className={`mt-1 text-right text-[9px] ${item.senderRole==="CUSTOMER"?"text-slate-400":"text-blue-200"}`}>{date(item.createdAt)}</div></div></div>)}{!chatLoading&&!messages.length&&<div className="py-20 text-center"><MessageCircle className="mx-auto text-slate-300"/><p className="mt-3 text-xs text-slate-400">No messages on this ticket.</p></div>}</div>{(admin||assignedToMe)?<div className="border-t p-4"><textarea value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}}} className="min-h-20 w-full resize-none rounded-xl border p-3 text-sm outline-none focus:border-brand" placeholder="Reply to the customer…"/><button disabled={busy||!message.trim()} onClick={sendMessage} className="mt-2 flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-brand text-sm font-bold text-white disabled:opacity-40"><Send size={16}/>Send reply</button></div>:<div className="border-t bg-amber-50 p-4 text-xs leading-5 text-amber-700">Assign this ticket to yourself before joining the customer conversation.</div>}</section>
   </div>:<div className="card grid min-h-[720px] place-items-center p-10 text-center"><div><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-blue-50 text-brand"><Ticket size={28}/></div><h2 className="mt-4 text-lg font-bold">Select a ticket from the queue</h2><p className="mt-2 max-w-md text-sm text-slate-500">Review the problem, establish ownership, update its service status and communicate with the customer.</p></div></div>}</main>
  </div>
 </div>;
}
