import {useEffect,useMemo,useState} from "react";
import {Bell,LogOut,MessageCircle,RefreshCw,Send,Store} from "lucide-react";
import {get,send} from "./api";

const tone={SENT_TO_VENDOR:"bg-amber-50 text-amber-700",VENDOR_ACCEPTED:"bg-blue-50 text-blue-700",IN_PROGRESS:"bg-violet-50 text-violet-700",RESOLVED:"bg-emerald-50 text-emerald-700"};
export default function VendorPortal({user,onLogout,embedded=false}){
 const[orders,setOrders]=useState([]),[orderView,setOrderView]=useState("ACTIVE"),[notifications,setNotifications]=useState([]),[selected,setSelected]=useState(),[quotes,setQuotes]=useState([]),[messages,setMessages]=useState([]),[amount,setAmount]=useState(""),[days,setDays]=useState(""),[terms,setTerms]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[tab,setTab]=useState("orders");
 const load=()=>Promise.all([get('/requirements?view=vendor'),get('/notifications')]).then(async([r,n])=>{const raw=Array.isArray(r)?r:[];const enriched=await Promise.all(raw.map(async o=>{const mine=await get(`/requirements/${o.id}/quotations?view=vendor`).catch(()=>[]);return {...o,vendorQuoteStatus:mine[0]?.status}}));setOrders(enriched);setNotifications(Array.isArray(n)?n:[])});useEffect(()=>{load()},[]);
 async function open(order){setSelected(order);const[q,m]=await Promise.all([get(`/requirements/${order.id}/quotations?view=vendor`).catch(()=>[]),get(`/requirements/${order.id}/messages`).catch(()=>[])]);setQuotes(q);setMessages(m);const mine=q[0];if(mine){setAmount(mine.amount||"");setDays(mine.leadTimeDays||"");setTerms(mine.notes||"")}}
 async function submitQuote(){if(!selected||!Number(amount)||!Number(days))return;setBusy(true);try{await send(`/requirements/${selected.id}/quotations/submit`,'PATCH',{amount,leadTimeDays:days,notes:terms});await open(selected);await load()}finally{setBusy(false)}}
 async function update(action){if(!selected)return;if(action==='start')await send(`/requirements/${selected.id}/start`,'PATCH',{});if(action==='resolve')await send(`/requirements/${selected.id}/resolve`,'PATCH',{resolution:terms||'Requirement completed'});await load();setSelected()}
 async function sendChat(){if(!selected||!message.trim())return;await send(`/requirements/${selected.id}/messages`,'POST',{message,senderName:user.name,senderRole:'VENDOR'});setMessage('');setMessages(await get(`/requirements/${selected.id}/messages`))}
 const unread=useMemo(()=>notifications.filter(n=>!n.read).length,[notifications]);
 const visibleOrders=useMemo(()=>orders.filter(o=>{const historical=["RESOLVED","CLOSED","REJECTED"].includes(o.status)||o.vendorQuoteStatus==='NOT_SELECTED';return orderView==='HISTORY'?historical:!historical}),[orders,orderView]);
 return <div className={`${embedded ? "min-h-[calc(100vh-80px)]" : "min-h-screen"} bg-slate-50`}>{!embedded&&<header className="flex h-20 items-center justify-between bg-navy px-5 text-white lg:px-10"><div><b className="text-lg">Wefyx Vendor Portal</b><p className="text-xs text-blue-200">Quotation requests, awarded orders and customer fulfilment</p></div><div className="flex items-center gap-4"><button onClick={()=>setTab('notifications')} className="relative"><Bell size={20}/>{unread>0&&<span className="absolute -right-2 -top-2 rounded-full bg-red-500 px-1 text-[9px]">{unread}</span>}</button><span className="hidden text-sm sm:block">{user.name}</span><button onClick={onLogout} className="flex items-center gap-2 rounded-lg border border-white/20 px-3 py-2 text-xs"><LogOut size={15}/>Sign out</button></div></header>}<main className="mx-auto max-w-6xl p-4 lg:p-8"><section className="mb-5 rounded-2xl bg-gradient-to-r from-blue-700 to-violet-600 p-6 text-white"><Store size={24}/><h1 className="mt-3 text-2xl font-bold">Vendor workspace</h1><p className="mt-1 text-sm text-blue-100">Respond to customer requirements, submit quotations and coordinate with Wefyx employees.</p></section>
 {tab==='notifications'?<section className="card overflow-hidden"><div className="flex items-center justify-between border-b p-5"><h2 className="font-bold">Notifications</h2><button onClick={()=>setTab('orders')} className="text-xs font-semibold text-brand">Back to orders</button></div>{notifications.map(n=><button key={n.id} onClick={async()=>{await send(`/notifications/${n.id}/read`,'PATCH',{});setTab('orders');const order=orders.find(o=>o.id===n.requirementId);if(order)open(order)}} className="flex w-full gap-3 border-b p-5 text-left hover:bg-blue-50"><Bell className="text-brand" size={18}/><div><b className="text-sm">{n.title}</b><p className="mt-1 text-xs text-slate-500">{n.message}</p></div></button>)}</section>:<section className="card overflow-hidden"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h2 className="font-bold">Vendor orders</h2><p className="text-xs text-slate-500">Active fulfilment and completed order history</p></div><div className="flex rounded-xl bg-slate-100 p-1"><button onClick={()=>setOrderView('ACTIVE')} className={`rounded-lg px-4 py-2 text-xs font-semibold ${orderView==='ACTIVE'?'bg-white text-brand shadow-sm':'text-slate-500'}`}>Active orders</button><button onClick={()=>setOrderView('HISTORY')} className={`rounded-lg px-4 py-2 text-xs font-semibold ${orderView==='HISTORY'?'bg-white text-brand shadow-sm':'text-slate-500'}`}>Order history</button></div><button onClick={load}><RefreshCw size={17}/></button></div><div className="divide-y">{visibleOrders.map(o=><button key={o.id} onClick={()=>open(o)} className="grid w-full gap-3 p-5 text-left hover:bg-slate-50 md:grid-cols-[1fr_auto]"><div><b className="text-sm">{o.title}</b><p className="mt-1 text-xs text-slate-500">{o.reference} · {o.organization||o.customerName} · {o.category}</p></div><span className={`pill ${tone[o.status]||'bg-slate-100'}`}>{o.status.replaceAll('_',' ')}</span></button>)}{!visibleOrders.length&&<div className="p-12 text-center text-sm text-slate-400">No {orderView==='HISTORY'?'completed orders':'active orders'} found.</div>}</div></section>}
 {selected&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6"><h3 className="text-lg font-bold">{selected.reference} · {selected.title}</h3><p className="mt-2 text-sm text-slate-600">{selected.description}</p>{selected.quotationRequested&&<section className="mt-5 rounded-xl border p-4"><h4 className="text-sm font-bold">Your quotation</h4><div className="mt-3 grid gap-3 sm:grid-cols-2"><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} className="h-11 rounded-xl border px-3 text-sm" placeholder="Amount (AED)"/><input type="number" value={days} onChange={e=>setDays(e.target.value)} className="h-11 rounded-xl border px-3 text-sm" placeholder="Completion days"/></div><textarea value={terms} onChange={e=>setTerms(e.target.value)} className="mt-3 min-h-20 w-full rounded-xl border p-3 text-sm" placeholder="Scope, terms and exclusions"/><button disabled={busy||['SELECTED','NOT_SELECTED'].includes(quotes[0]?.status)} onClick={submitQuote} className="mt-3 rounded-xl bg-brand px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Submit quotation</button>{quotes[0]&&<p className="mt-3 text-xs text-slate-500">Current status: {quotes[0].status.replaceAll('_',' ')}</p>}</section>}<section className="mt-5 rounded-xl border p-4"><h4 className="flex items-center gap-2 text-sm font-bold"><MessageCircle size={17}/>Order chat</h4><div className="mt-3 max-h-44 space-y-2 overflow-y-auto">{messages.map(m=><div key={m.id} className="rounded-xl bg-slate-50 p-3"><b className="text-[10px] text-brand">{m.senderName} · {m.senderRole}</b><p className="mt-1 text-sm">{m.message}</p></div>)}</div><div className="mt-3 flex gap-2"><input value={message} onChange={e=>setMessage(e.target.value)} className="h-11 flex-1 rounded-xl border px-3 text-sm" placeholder="Reply to Wefyx employee"/><button onClick={sendChat} className="rounded-xl bg-brand px-4 text-white"><Send size={16}/></button></div></section><div className="mt-5 flex flex-wrap gap-2">{selected.status==='VENDOR_ACCEPTED'&&quotes[0]?.status==='SELECTED'&&<button onClick={()=>update('start')} className="rounded-xl bg-brand px-4 py-2 text-sm font-semibold text-white">Start fulfilment</button>}{selected.status==='IN_PROGRESS'&&quotes[0]?.status==='SELECTED'&&<button onClick={()=>update('resolve')} className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-semibold text-white">Mark completed</button>}<button onClick={()=>setSelected()} className="ml-auto px-4 py-2 text-sm">Close</button></div></div></div>}</main></div>
}
